// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"go-wind-oa/app/oa/service/internal/data"
	"go-wind-oa/app/oa/service/internal/data/client"
	"go-wind-oa/app/oa/service/internal/server"
	"go-wind-oa/app/oa/service/internal/service"
)

import (
	_ "github.com/tx7do/kratos-bootstrap/registry/etcd"
	_ "github.com/tx7do/kratos-bootstrap/tracer"
)

// Injectors from wire.go:

// initApp init kratos application.
//
// 与 go-wind-cms/app/admin/service/cmd/server/wire.go 同构：仅 wire.Build
// 三个 provider set + newApp，无额外绑定。OA 仅起 HTTP server，故 newApp 只接收
// *http.Server（无 gRPC / SSE server）。
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	v := server.NewRestMiddleware(context)
	entClient, cleanup, err := client.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	workflowDefinitionRepo := data.NewWorkflowDefinitionRepo(context, entClient)
	workflowInstanceRepo := data.NewWorkflowInstanceRepo(context, entClient)
	workflowTaskRepo := data.NewWorkflowTaskRepo(context, entClient)
	workflowLogRepo := data.NewWorkflowLogRepo(context, entClient)
	discovery := data.NewDiscovery(context)
	internalMessageServiceClient := data.NewNotificationServiceClient(context, discovery)
	workflowService := service.NewWorkflowService(context, workflowDefinitionRepo, workflowInstanceRepo, workflowTaskRepo, workflowLogRepo, internalMessageServiceClient)
	authenticationServiceClient := data.NewAuthenticationServiceClient(context, discovery)
	authenticationService := service.NewAuthenticationService(context, authenticationServiceClient)
	httpServer := server.NewRestServer(context, v, workflowService, authenticationService)
	app := newApp(context, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
