// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"go-wind-oa/app/app/service/internal/data"
	"go-wind-oa/app/app/service/internal/server"
	"go-wind-oa/app/app/service/internal/service"
	"go-wind-oa/pkg/middleware/auth"
)

import (
	_ "github.com/tx7do/kratos-bootstrap/registry/etcd"
	_ "github.com/tx7do/kratos-bootstrap/tracer"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(context)
	authenticationServiceClient := data.NewAuthenticationServiceClient(context, discovery)
	clientType := data.NewClientType()
	accessTokenChecker := auth.NewTokenChecker(context, authenticationServiceClient, clientType)
	engine := data.NewAuthorizer()
	v := server.NewRestMiddleware(context, accessTokenChecker, engine)
	authenticationService := service.NewAuthenticationService(context, authenticationServiceClient)
	workflowServiceClient := data.NewWorkflowServiceClient(context, discovery)
	workflowService := service.NewWorkflowService(context, workflowServiceClient)
	internalMessageServiceClient := data.NewInternalMessageServiceClient(context, discovery)
	internalMessageService := service.NewInternalMessageService(context, internalMessageServiceClient)
	httpServer := server.NewRestServer(context, v, authenticationService, workflowService, internalMessageService)
	grpcMiddlewares := server.NewGrpcMiddleware(context)
	grpcServer, err := server.NewGrpcServer(context, grpcMiddlewares)
	if err != nil {
		return nil, nil, err
	}
	sseServer := server.NewSseServer(context, authenticationServiceClient)
	app := newApp(context, httpServer, grpcServer, sseServer)
	return app, func() {
	}, nil
}
