// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-oa/app/oa/service/internal/data/ent/workflowinstance"
	"go-wind-oa/app/oa/service/internal/data/ent/workflowtask"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// OA工作流任务表
type WorkflowTask struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 节点序号
	NodeIndex *int32 `json:"node_index,omitempty"`
	// 指派审批人
	AssigneeUserID *uint32 `json:"assignee_user_id,omitempty"`
	// 任务状态
	TaskStatus workflowtask.TaskStatus `json:"task_status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkflowTaskQuery when eager-loading is set.
	Edges        WorkflowTaskEdges `json:"edges"`
	instance_id  *uint32
	selectValues sql.SelectValues
}

// WorkflowTaskEdges holds the relations/edges for other nodes in the graph.
type WorkflowTaskEdges struct {
	// Instance holds the value of the instance edge.
	Instance *WorkflowInstance `json:"instance,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// InstanceOrErr returns the Instance value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkflowTaskEdges) InstanceOrErr() (*WorkflowInstance, error) {
	if e.Instance != nil {
		return e.Instance, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workflowinstance.Label}
	}
	return nil, &NotLoadedError{edge: "instance"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkflowTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workflowtask.FieldID, workflowtask.FieldCreatedBy, workflowtask.FieldUpdatedBy, workflowtask.FieldDeletedBy, workflowtask.FieldTenantID, workflowtask.FieldNodeIndex, workflowtask.FieldAssigneeUserID:
			values[i] = new(sql.NullInt64)
		case workflowtask.FieldTaskStatus:
			values[i] = new(sql.NullString)
		case workflowtask.FieldCreatedAt, workflowtask.FieldUpdatedAt, workflowtask.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case workflowtask.ForeignKeys[0]: // instance_id
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkflowTask fields.
func (_m *WorkflowTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workflowtask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case workflowtask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case workflowtask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case workflowtask.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case workflowtask.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case workflowtask.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case workflowtask.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case workflowtask.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case workflowtask.FieldNodeIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field node_index", values[i])
			} else if value.Valid {
				_m.NodeIndex = new(int32)
				*_m.NodeIndex = int32(value.Int64)
			}
		case workflowtask.FieldAssigneeUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assignee_user_id", values[i])
			} else if value.Valid {
				_m.AssigneeUserID = new(uint32)
				*_m.AssigneeUserID = uint32(value.Int64)
			}
		case workflowtask.FieldTaskStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_status", values[i])
			} else if value.Valid {
				_m.TaskStatus = workflowtask.TaskStatus(value.String)
			}
		case workflowtask.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field instance_id", value)
			} else if value.Valid {
				_m.instance_id = new(uint32)
				*_m.instance_id = uint32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkflowTask.
// This includes values selected through modifiers, order, etc.
func (_m *WorkflowTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInstance queries the "instance" edge of the WorkflowTask entity.
func (_m *WorkflowTask) QueryInstance() *WorkflowInstanceQuery {
	return NewWorkflowTaskClient(_m.config).QueryInstance(_m)
}

// Update returns a builder for updating this WorkflowTask.
// Note that you need to call WorkflowTask.Unwrap() before calling this method if this WorkflowTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkflowTask) Update() *WorkflowTaskUpdateOne {
	return NewWorkflowTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkflowTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkflowTask) Unwrap() *WorkflowTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkflowTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkflowTask) String() string {
	var builder strings.Builder
	builder.WriteString("WorkflowTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.NodeIndex; v != nil {
		builder.WriteString("node_index=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AssigneeUserID; v != nil {
		builder.WriteString("assignee_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("task_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskStatus))
	builder.WriteByte(')')
	return builder.String()
}

// WorkflowTasks is a parsable slice of WorkflowTask.
type WorkflowTasks []*WorkflowTask
