// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-oa/app/core/service/internal/data/ent/attendancerecord"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// OA 考勤打卡记录表（用户 x 工作日 唯一）
type AttendanceRecord struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 用户ID
	UserID uint32 `json:"user_id,omitempty"`
	// 工作日（日期，零点）
	WorkDate time.Time `json:"work_date,omitempty"`
	// 上班签到时间
	CheckInAt *time.Time `json:"check_in_at,omitempty"`
	// 签到 GPS 纬度
	CheckInLatitude *float64 `json:"check_in_latitude,omitempty"`
	// 签到 GPS 经度
	CheckInLongitude *float64 `json:"check_in_longitude,omitempty"`
	// 签到 Wifi BSSID
	CheckInWifiBssid *string `json:"check_in_wifi_bssid,omitempty"`
	// 下班签退时间
	CheckOutAt *time.Time `json:"check_out_at,omitempty"`
	// 签退 GPS 纬度
	CheckOutLatitude *float64 `json:"check_out_latitude,omitempty"`
	// 签退 GPS 经度
	CheckOutLongitude *float64 `json:"check_out_longitude,omitempty"`
	// 签退 Wifi BSSID
	CheckOutWifiBssid *string `json:"check_out_wifi_bssid,omitempty"`
	// 当日结算结果
	DayResult    *attendancerecord.DayResult `json:"day_result,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AttendanceRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case attendancerecord.FieldCheckInLatitude, attendancerecord.FieldCheckInLongitude, attendancerecord.FieldCheckOutLatitude, attendancerecord.FieldCheckOutLongitude:
			values[i] = new(sql.NullFloat64)
		case attendancerecord.FieldID, attendancerecord.FieldCreatedBy, attendancerecord.FieldUpdatedBy, attendancerecord.FieldDeletedBy, attendancerecord.FieldTenantID, attendancerecord.FieldUserID:
			values[i] = new(sql.NullInt64)
		case attendancerecord.FieldCheckInWifiBssid, attendancerecord.FieldCheckOutWifiBssid, attendancerecord.FieldDayResult:
			values[i] = new(sql.NullString)
		case attendancerecord.FieldCreatedAt, attendancerecord.FieldUpdatedAt, attendancerecord.FieldDeletedAt, attendancerecord.FieldWorkDate, attendancerecord.FieldCheckInAt, attendancerecord.FieldCheckOutAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AttendanceRecord fields.
func (_m *AttendanceRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case attendancerecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case attendancerecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case attendancerecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case attendancerecord.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case attendancerecord.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case attendancerecord.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case attendancerecord.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case attendancerecord.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case attendancerecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint32(value.Int64)
			}
		case attendancerecord.FieldWorkDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field work_date", values[i])
			} else if value.Valid {
				_m.WorkDate = value.Time
			}
		case attendancerecord.FieldCheckInAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field check_in_at", values[i])
			} else if value.Valid {
				_m.CheckInAt = new(time.Time)
				*_m.CheckInAt = value.Time
			}
		case attendancerecord.FieldCheckInLatitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field check_in_latitude", values[i])
			} else if value.Valid {
				_m.CheckInLatitude = new(float64)
				*_m.CheckInLatitude = value.Float64
			}
		case attendancerecord.FieldCheckInLongitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field check_in_longitude", values[i])
			} else if value.Valid {
				_m.CheckInLongitude = new(float64)
				*_m.CheckInLongitude = value.Float64
			}
		case attendancerecord.FieldCheckInWifiBssid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field check_in_wifi_bssid", values[i])
			} else if value.Valid {
				_m.CheckInWifiBssid = new(string)
				*_m.CheckInWifiBssid = value.String
			}
		case attendancerecord.FieldCheckOutAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field check_out_at", values[i])
			} else if value.Valid {
				_m.CheckOutAt = new(time.Time)
				*_m.CheckOutAt = value.Time
			}
		case attendancerecord.FieldCheckOutLatitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field check_out_latitude", values[i])
			} else if value.Valid {
				_m.CheckOutLatitude = new(float64)
				*_m.CheckOutLatitude = value.Float64
			}
		case attendancerecord.FieldCheckOutLongitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field check_out_longitude", values[i])
			} else if value.Valid {
				_m.CheckOutLongitude = new(float64)
				*_m.CheckOutLongitude = value.Float64
			}
		case attendancerecord.FieldCheckOutWifiBssid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field check_out_wifi_bssid", values[i])
			} else if value.Valid {
				_m.CheckOutWifiBssid = new(string)
				*_m.CheckOutWifiBssid = value.String
			}
		case attendancerecord.FieldDayResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field day_result", values[i])
			} else if value.Valid {
				_m.DayResult = new(attendancerecord.DayResult)
				*_m.DayResult = attendancerecord.DayResult(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AttendanceRecord.
// This includes values selected through modifiers, order, etc.
func (_m *AttendanceRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AttendanceRecord.
// Note that you need to call AttendanceRecord.Unwrap() before calling this method if this AttendanceRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AttendanceRecord) Update() *AttendanceRecordUpdateOne {
	return NewAttendanceRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AttendanceRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AttendanceRecord) Unwrap() *AttendanceRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AttendanceRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AttendanceRecord) String() string {
	var builder strings.Builder
	builder.WriteString("AttendanceRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("work_date=")
	builder.WriteString(_m.WorkDate.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CheckInAt; v != nil {
		builder.WriteString("check_in_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CheckInLatitude; v != nil {
		builder.WriteString("check_in_latitude=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CheckInLongitude; v != nil {
		builder.WriteString("check_in_longitude=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CheckInWifiBssid; v != nil {
		builder.WriteString("check_in_wifi_bssid=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CheckOutAt; v != nil {
		builder.WriteString("check_out_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CheckOutLatitude; v != nil {
		builder.WriteString("check_out_latitude=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CheckOutLongitude; v != nil {
		builder.WriteString("check_out_longitude=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CheckOutWifiBssid; v != nil {
		builder.WriteString("check_out_wifi_bssid=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DayResult; v != nil {
		builder.WriteString("day_result=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AttendanceRecords is a parsable slice of AttendanceRecord.
type AttendanceRecords []*AttendanceRecord
