// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-oa/app/core/service/internal/data/ent/expenseapplication"
	"go-wind-oa/app/core/service/internal/data/ent/expenseitem"
	"go-wind-oa/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExpenseItemUpdate is the builder for updating ExpenseItem entities.
type ExpenseItemUpdate struct {
	config
	hooks     []Hook
	mutation  *ExpenseItemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ExpenseItemUpdate builder.
func (_u *ExpenseItemUpdate) Where(ps ...predicate.ExpenseItem) *ExpenseItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExpenseItemUpdate) SetUpdatedAt(v time.Time) *ExpenseItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ExpenseItemUpdate) SetNillableUpdatedAt(v *time.Time) *ExpenseItemUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ExpenseItemUpdate) ClearUpdatedAt() *ExpenseItemUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ExpenseItemUpdate) SetDeletedAt(v time.Time) *ExpenseItemUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ExpenseItemUpdate) SetNillableDeletedAt(v *time.Time) *ExpenseItemUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ExpenseItemUpdate) ClearDeletedAt() *ExpenseItemUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ExpenseItemUpdate) SetCreatedBy(v uint32) *ExpenseItemUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ExpenseItemUpdate) SetNillableCreatedBy(v *uint32) *ExpenseItemUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ExpenseItemUpdate) AddCreatedBy(v int32) *ExpenseItemUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ExpenseItemUpdate) ClearCreatedBy() *ExpenseItemUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ExpenseItemUpdate) SetUpdatedBy(v uint32) *ExpenseItemUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ExpenseItemUpdate) SetNillableUpdatedBy(v *uint32) *ExpenseItemUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ExpenseItemUpdate) AddUpdatedBy(v int32) *ExpenseItemUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ExpenseItemUpdate) ClearUpdatedBy() *ExpenseItemUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ExpenseItemUpdate) SetDeletedBy(v uint32) *ExpenseItemUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ExpenseItemUpdate) SetNillableDeletedBy(v *uint32) *ExpenseItemUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ExpenseItemUpdate) AddDeletedBy(v int32) *ExpenseItemUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ExpenseItemUpdate) ClearDeletedBy() *ExpenseItemUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetCategory sets the "category" field.
func (_u *ExpenseItemUpdate) SetCategory(v string) *ExpenseItemUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ExpenseItemUpdate) SetNillableCategory(v *string) *ExpenseItemUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ExpenseItemUpdate) SetAmount(v float64) *ExpenseItemUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ExpenseItemUpdate) SetNillableAmount(v *float64) *ExpenseItemUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ExpenseItemUpdate) AddAmount(v float64) *ExpenseItemUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetExpenseDate sets the "expense_date" field.
func (_u *ExpenseItemUpdate) SetExpenseDate(v time.Time) *ExpenseItemUpdate {
	_u.mutation.SetExpenseDate(v)
	return _u
}

// SetNillableExpenseDate sets the "expense_date" field if the given value is not nil.
func (_u *ExpenseItemUpdate) SetNillableExpenseDate(v *time.Time) *ExpenseItemUpdate {
	if v != nil {
		_u.SetExpenseDate(*v)
	}
	return _u
}

// ClearExpenseDate clears the value of the "expense_date" field.
func (_u *ExpenseItemUpdate) ClearExpenseDate() *ExpenseItemUpdate {
	_u.mutation.ClearExpenseDate()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ExpenseItemUpdate) SetDescription(v string) *ExpenseItemUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ExpenseItemUpdate) SetNillableDescription(v *string) *ExpenseItemUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetInvoiceFileID sets the "invoice_file_id" field.
func (_u *ExpenseItemUpdate) SetInvoiceFileID(v uint32) *ExpenseItemUpdate {
	_u.mutation.ResetInvoiceFileID()
	_u.mutation.SetInvoiceFileID(v)
	return _u
}

// SetNillableInvoiceFileID sets the "invoice_file_id" field if the given value is not nil.
func (_u *ExpenseItemUpdate) SetNillableInvoiceFileID(v *uint32) *ExpenseItemUpdate {
	if v != nil {
		_u.SetInvoiceFileID(*v)
	}
	return _u
}

// AddInvoiceFileID adds value to the "invoice_file_id" field.
func (_u *ExpenseItemUpdate) AddInvoiceFileID(v int32) *ExpenseItemUpdate {
	_u.mutation.AddInvoiceFileID(v)
	return _u
}

// ClearInvoiceFileID clears the value of the "invoice_file_id" field.
func (_u *ExpenseItemUpdate) ClearInvoiceFileID() *ExpenseItemUpdate {
	_u.mutation.ClearInvoiceFileID()
	return _u
}

// SetApplicationID sets the "application" edge to the ExpenseApplication entity by ID.
func (_u *ExpenseItemUpdate) SetApplicationID(id uint32) *ExpenseItemUpdate {
	_u.mutation.SetApplicationID(id)
	return _u
}

// SetNillableApplicationID sets the "application" edge to the ExpenseApplication entity by ID if the given value is not nil.
func (_u *ExpenseItemUpdate) SetNillableApplicationID(id *uint32) *ExpenseItemUpdate {
	if id != nil {
		_u = _u.SetApplicationID(*id)
	}
	return _u
}

// SetApplication sets the "application" edge to the ExpenseApplication entity.
func (_u *ExpenseItemUpdate) SetApplication(v *ExpenseApplication) *ExpenseItemUpdate {
	return _u.SetApplicationID(v.ID)
}

// Mutation returns the ExpenseItemMutation object of the builder.
func (_u *ExpenseItemUpdate) Mutation() *ExpenseItemMutation {
	return _u.mutation
}

// ClearApplication clears the "application" edge to the ExpenseApplication entity.
func (_u *ExpenseItemUpdate) ClearApplication() *ExpenseItemUpdate {
	_u.mutation.ClearApplication()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExpenseItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExpenseItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExpenseItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExpenseItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExpenseItemUpdate) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := expenseitem.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ExpenseItem.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := expenseitem.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ExpenseItem.description": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ExpenseItemUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ExpenseItemUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ExpenseItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(expenseitem.Table, expenseitem.Columns, sqlgraph.NewFieldSpec(expenseitem.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(expenseitem.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(expenseitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(expenseitem.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(expenseitem.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(expenseitem.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(expenseitem.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(expenseitem.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(expenseitem.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(expenseitem.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(expenseitem.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(expenseitem.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(expenseitem.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(expenseitem.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(expenseitem.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(expenseitem.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(expenseitem.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(expenseitem.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(expenseitem.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExpenseDate(); ok {
		_spec.SetField(expenseitem.FieldExpenseDate, field.TypeTime, value)
	}
	if _u.mutation.ExpenseDateCleared() {
		_spec.ClearField(expenseitem.FieldExpenseDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(expenseitem.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceFileID(); ok {
		_spec.SetField(expenseitem.FieldInvoiceFileID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedInvoiceFileID(); ok {
		_spec.AddField(expenseitem.FieldInvoiceFileID, field.TypeUint32, value)
	}
	if _u.mutation.InvoiceFileIDCleared() {
		_spec.ClearField(expenseitem.FieldInvoiceFileID, field.TypeUint32)
	}
	if _u.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expenseitem.ApplicationTable,
			Columns: []string{expenseitem.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expenseapplication.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expenseitem.ApplicationTable,
			Columns: []string{expenseitem.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expenseapplication.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{expenseitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExpenseItemUpdateOne is the builder for updating a single ExpenseItem entity.
type ExpenseItemUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ExpenseItemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExpenseItemUpdateOne) SetUpdatedAt(v time.Time) *ExpenseItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ExpenseItemUpdateOne) SetNillableUpdatedAt(v *time.Time) *ExpenseItemUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ExpenseItemUpdateOne) ClearUpdatedAt() *ExpenseItemUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ExpenseItemUpdateOne) SetDeletedAt(v time.Time) *ExpenseItemUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ExpenseItemUpdateOne) SetNillableDeletedAt(v *time.Time) *ExpenseItemUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ExpenseItemUpdateOne) ClearDeletedAt() *ExpenseItemUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ExpenseItemUpdateOne) SetCreatedBy(v uint32) *ExpenseItemUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ExpenseItemUpdateOne) SetNillableCreatedBy(v *uint32) *ExpenseItemUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ExpenseItemUpdateOne) AddCreatedBy(v int32) *ExpenseItemUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ExpenseItemUpdateOne) ClearCreatedBy() *ExpenseItemUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ExpenseItemUpdateOne) SetUpdatedBy(v uint32) *ExpenseItemUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ExpenseItemUpdateOne) SetNillableUpdatedBy(v *uint32) *ExpenseItemUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ExpenseItemUpdateOne) AddUpdatedBy(v int32) *ExpenseItemUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ExpenseItemUpdateOne) ClearUpdatedBy() *ExpenseItemUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *ExpenseItemUpdateOne) SetDeletedBy(v uint32) *ExpenseItemUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *ExpenseItemUpdateOne) SetNillableDeletedBy(v *uint32) *ExpenseItemUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *ExpenseItemUpdateOne) AddDeletedBy(v int32) *ExpenseItemUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *ExpenseItemUpdateOne) ClearDeletedBy() *ExpenseItemUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetCategory sets the "category" field.
func (_u *ExpenseItemUpdateOne) SetCategory(v string) *ExpenseItemUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ExpenseItemUpdateOne) SetNillableCategory(v *string) *ExpenseItemUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ExpenseItemUpdateOne) SetAmount(v float64) *ExpenseItemUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ExpenseItemUpdateOne) SetNillableAmount(v *float64) *ExpenseItemUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ExpenseItemUpdateOne) AddAmount(v float64) *ExpenseItemUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetExpenseDate sets the "expense_date" field.
func (_u *ExpenseItemUpdateOne) SetExpenseDate(v time.Time) *ExpenseItemUpdateOne {
	_u.mutation.SetExpenseDate(v)
	return _u
}

// SetNillableExpenseDate sets the "expense_date" field if the given value is not nil.
func (_u *ExpenseItemUpdateOne) SetNillableExpenseDate(v *time.Time) *ExpenseItemUpdateOne {
	if v != nil {
		_u.SetExpenseDate(*v)
	}
	return _u
}

// ClearExpenseDate clears the value of the "expense_date" field.
func (_u *ExpenseItemUpdateOne) ClearExpenseDate() *ExpenseItemUpdateOne {
	_u.mutation.ClearExpenseDate()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ExpenseItemUpdateOne) SetDescription(v string) *ExpenseItemUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ExpenseItemUpdateOne) SetNillableDescription(v *string) *ExpenseItemUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetInvoiceFileID sets the "invoice_file_id" field.
func (_u *ExpenseItemUpdateOne) SetInvoiceFileID(v uint32) *ExpenseItemUpdateOne {
	_u.mutation.ResetInvoiceFileID()
	_u.mutation.SetInvoiceFileID(v)
	return _u
}

// SetNillableInvoiceFileID sets the "invoice_file_id" field if the given value is not nil.
func (_u *ExpenseItemUpdateOne) SetNillableInvoiceFileID(v *uint32) *ExpenseItemUpdateOne {
	if v != nil {
		_u.SetInvoiceFileID(*v)
	}
	return _u
}

// AddInvoiceFileID adds value to the "invoice_file_id" field.
func (_u *ExpenseItemUpdateOne) AddInvoiceFileID(v int32) *ExpenseItemUpdateOne {
	_u.mutation.AddInvoiceFileID(v)
	return _u
}

// ClearInvoiceFileID clears the value of the "invoice_file_id" field.
func (_u *ExpenseItemUpdateOne) ClearInvoiceFileID() *ExpenseItemUpdateOne {
	_u.mutation.ClearInvoiceFileID()
	return _u
}

// SetApplicationID sets the "application" edge to the ExpenseApplication entity by ID.
func (_u *ExpenseItemUpdateOne) SetApplicationID(id uint32) *ExpenseItemUpdateOne {
	_u.mutation.SetApplicationID(id)
	return _u
}

// SetNillableApplicationID sets the "application" edge to the ExpenseApplication entity by ID if the given value is not nil.
func (_u *ExpenseItemUpdateOne) SetNillableApplicationID(id *uint32) *ExpenseItemUpdateOne {
	if id != nil {
		_u = _u.SetApplicationID(*id)
	}
	return _u
}

// SetApplication sets the "application" edge to the ExpenseApplication entity.
func (_u *ExpenseItemUpdateOne) SetApplication(v *ExpenseApplication) *ExpenseItemUpdateOne {
	return _u.SetApplicationID(v.ID)
}

// Mutation returns the ExpenseItemMutation object of the builder.
func (_u *ExpenseItemUpdateOne) Mutation() *ExpenseItemMutation {
	return _u.mutation
}

// ClearApplication clears the "application" edge to the ExpenseApplication entity.
func (_u *ExpenseItemUpdateOne) ClearApplication() *ExpenseItemUpdateOne {
	_u.mutation.ClearApplication()
	return _u
}

// Where appends a list predicates to the ExpenseItemUpdate builder.
func (_u *ExpenseItemUpdateOne) Where(ps ...predicate.ExpenseItem) *ExpenseItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExpenseItemUpdateOne) Select(field string, fields ...string) *ExpenseItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ExpenseItem entity.
func (_u *ExpenseItemUpdateOne) Save(ctx context.Context) (*ExpenseItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExpenseItemUpdateOne) SaveX(ctx context.Context) *ExpenseItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExpenseItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExpenseItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExpenseItemUpdateOne) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := expenseitem.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ExpenseItem.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := expenseitem.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ExpenseItem.description": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ExpenseItemUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ExpenseItemUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ExpenseItemUpdateOne) sqlSave(ctx context.Context) (_node *ExpenseItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(expenseitem.Table, expenseitem.Columns, sqlgraph.NewFieldSpec(expenseitem.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExpenseItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, expenseitem.FieldID)
		for _, f := range fields {
			if !expenseitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != expenseitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(expenseitem.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(expenseitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(expenseitem.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(expenseitem.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(expenseitem.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(expenseitem.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(expenseitem.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(expenseitem.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(expenseitem.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(expenseitem.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(expenseitem.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(expenseitem.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(expenseitem.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(expenseitem.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(expenseitem.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(expenseitem.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(expenseitem.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(expenseitem.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExpenseDate(); ok {
		_spec.SetField(expenseitem.FieldExpenseDate, field.TypeTime, value)
	}
	if _u.mutation.ExpenseDateCleared() {
		_spec.ClearField(expenseitem.FieldExpenseDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(expenseitem.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceFileID(); ok {
		_spec.SetField(expenseitem.FieldInvoiceFileID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedInvoiceFileID(); ok {
		_spec.AddField(expenseitem.FieldInvoiceFileID, field.TypeUint32, value)
	}
	if _u.mutation.InvoiceFileIDCleared() {
		_spec.ClearField(expenseitem.FieldInvoiceFileID, field.TypeUint32)
	}
	if _u.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expenseitem.ApplicationTable,
			Columns: []string{expenseitem.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expenseapplication.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expenseitem.ApplicationTable,
			Columns: []string{expenseitem.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expenseapplication.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ExpenseItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{expenseitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
