// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-oa/app/core/service/internal/data/ent/expenseapplication"
	"go-wind-oa/app/core/service/internal/data/ent/expenseitem"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExpenseApplicationCreate is the builder for creating a ExpenseApplication entity.
type ExpenseApplicationCreate struct {
	config
	mutation *ExpenseApplicationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExpenseApplicationCreate) SetCreatedAt(v time.Time) *ExpenseApplicationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExpenseApplicationCreate) SetNillableCreatedAt(v *time.Time) *ExpenseApplicationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExpenseApplicationCreate) SetUpdatedAt(v time.Time) *ExpenseApplicationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExpenseApplicationCreate) SetNillableUpdatedAt(v *time.Time) *ExpenseApplicationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ExpenseApplicationCreate) SetDeletedAt(v time.Time) *ExpenseApplicationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ExpenseApplicationCreate) SetNillableDeletedAt(v *time.Time) *ExpenseApplicationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ExpenseApplicationCreate) SetCreatedBy(v uint32) *ExpenseApplicationCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ExpenseApplicationCreate) SetNillableCreatedBy(v *uint32) *ExpenseApplicationCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ExpenseApplicationCreate) SetUpdatedBy(v uint32) *ExpenseApplicationCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ExpenseApplicationCreate) SetNillableUpdatedBy(v *uint32) *ExpenseApplicationCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *ExpenseApplicationCreate) SetDeletedBy(v uint32) *ExpenseApplicationCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *ExpenseApplicationCreate) SetNillableDeletedBy(v *uint32) *ExpenseApplicationCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ExpenseApplicationCreate) SetTenantID(v uint32) *ExpenseApplicationCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ExpenseApplicationCreate) SetNillableTenantID(v *uint32) *ExpenseApplicationCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *ExpenseApplicationCreate) SetTitle(v string) *ExpenseApplicationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *ExpenseApplicationCreate) SetNillableTitle(v *string) *ExpenseApplicationCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *ExpenseApplicationCreate) SetTotalAmount(v float64) *ExpenseApplicationCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_c *ExpenseApplicationCreate) SetNillableTotalAmount(v *float64) *ExpenseApplicationCreate {
	if v != nil {
		_c.SetTotalAmount(*v)
	}
	return _c
}

// SetExpenseStatus sets the "expense_status" field.
func (_c *ExpenseApplicationCreate) SetExpenseStatus(v expenseapplication.ExpenseStatus) *ExpenseApplicationCreate {
	_c.mutation.SetExpenseStatus(v)
	return _c
}

// SetNillableExpenseStatus sets the "expense_status" field if the given value is not nil.
func (_c *ExpenseApplicationCreate) SetNillableExpenseStatus(v *expenseapplication.ExpenseStatus) *ExpenseApplicationCreate {
	if v != nil {
		_c.SetExpenseStatus(*v)
	}
	return _c
}

// SetInstanceID sets the "instance_id" field.
func (_c *ExpenseApplicationCreate) SetInstanceID(v uint32) *ExpenseApplicationCreate {
	_c.mutation.SetInstanceID(v)
	return _c
}

// SetNillableInstanceID sets the "instance_id" field if the given value is not nil.
func (_c *ExpenseApplicationCreate) SetNillableInstanceID(v *uint32) *ExpenseApplicationCreate {
	if v != nil {
		_c.SetInstanceID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExpenseApplicationCreate) SetID(v uint32) *ExpenseApplicationCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddItemIDs adds the "items" edge to the ExpenseItem entity by IDs.
func (_c *ExpenseApplicationCreate) AddItemIDs(ids ...uint32) *ExpenseApplicationCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the ExpenseItem entity.
func (_c *ExpenseApplicationCreate) AddItems(v ...*ExpenseItem) *ExpenseApplicationCreate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the ExpenseApplicationMutation object of the builder.
func (_c *ExpenseApplicationCreate) Mutation() *ExpenseApplicationMutation {
	return _c.mutation
}

// Save creates the ExpenseApplication in the database.
func (_c *ExpenseApplicationCreate) Save(ctx context.Context) (*ExpenseApplication, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExpenseApplicationCreate) SaveX(ctx context.Context) *ExpenseApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExpenseApplicationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExpenseApplicationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExpenseApplicationCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := expenseapplication.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := expenseapplication.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		v := expenseapplication.DefaultTotalAmount
		_c.mutation.SetTotalAmount(v)
	}
	if _, ok := _c.mutation.ExpenseStatus(); !ok {
		v := expenseapplication.DefaultExpenseStatus
		_c.mutation.SetExpenseStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExpenseApplicationCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ExpenseApplication.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := expenseapplication.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ExpenseApplication.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "ExpenseApplication.total_amount"`)}
	}
	if v, ok := _c.mutation.ExpenseStatus(); ok {
		if err := expenseapplication.ExpenseStatusValidator(v); err != nil {
			return &ValidationError{Name: "expense_status", err: fmt.Errorf(`ent: validator failed for field "ExpenseApplication.expense_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := expenseapplication.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ExpenseApplication.id": %w`, err)}
		}
	}
	if len(_c.mutation.ItemsIDs()) == 0 {
		return &ValidationError{Name: "items", err: errors.New(`ent: missing required edge "ExpenseApplication.items"`)}
	}
	return nil
}

func (_c *ExpenseApplicationCreate) sqlSave(ctx context.Context) (*ExpenseApplication, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExpenseApplicationCreate) createSpec() (*ExpenseApplication, *sqlgraph.CreateSpec) {
	var (
		_node = &ExpenseApplication{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(expenseapplication.Table, sqlgraph.NewFieldSpec(expenseapplication.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(expenseapplication.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(expenseapplication.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(expenseapplication.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(expenseapplication.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(expenseapplication.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(expenseapplication.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(expenseapplication.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(expenseapplication.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(expenseapplication.FieldTotalAmount, field.TypeFloat64, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.ExpenseStatus(); ok {
		_spec.SetField(expenseapplication.FieldExpenseStatus, field.TypeEnum, value)
		_node.ExpenseStatus = &value
	}
	if value, ok := _c.mutation.InstanceID(); ok {
		_spec.SetField(expenseapplication.FieldInstanceID, field.TypeUint32, value)
		_node.InstanceID = &value
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   expenseapplication.ItemsTable,
			Columns: []string{expenseapplication.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expenseitem.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExpenseApplication.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExpenseApplicationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExpenseApplicationCreate) OnConflict(opts ...sql.ConflictOption) *ExpenseApplicationUpsertOne {
	_c.conflict = opts
	return &ExpenseApplicationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExpenseApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExpenseApplicationCreate) OnConflictColumns(columns ...string) *ExpenseApplicationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExpenseApplicationUpsertOne{
		create: _c,
	}
}

type (
	// ExpenseApplicationUpsertOne is the builder for "upsert"-ing
	//  one ExpenseApplication node.
	ExpenseApplicationUpsertOne struct {
		create *ExpenseApplicationCreate
	}

	// ExpenseApplicationUpsert is the "OnConflict" setter.
	ExpenseApplicationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ExpenseApplicationUpsert) SetUpdatedAt(v time.Time) *ExpenseApplicationUpsert {
	u.Set(expenseapplication.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExpenseApplicationUpsert) UpdateUpdatedAt() *ExpenseApplicationUpsert {
	u.SetExcluded(expenseapplication.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ExpenseApplicationUpsert) ClearUpdatedAt() *ExpenseApplicationUpsert {
	u.SetNull(expenseapplication.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ExpenseApplicationUpsert) SetDeletedAt(v time.Time) *ExpenseApplicationUpsert {
	u.Set(expenseapplication.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ExpenseApplicationUpsert) UpdateDeletedAt() *ExpenseApplicationUpsert {
	u.SetExcluded(expenseapplication.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ExpenseApplicationUpsert) ClearDeletedAt() *ExpenseApplicationUpsert {
	u.SetNull(expenseapplication.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ExpenseApplicationUpsert) SetCreatedBy(v uint32) *ExpenseApplicationUpsert {
	u.Set(expenseapplication.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExpenseApplicationUpsert) UpdateCreatedBy() *ExpenseApplicationUpsert {
	u.SetExcluded(expenseapplication.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ExpenseApplicationUpsert) AddCreatedBy(v uint32) *ExpenseApplicationUpsert {
	u.Add(expenseapplication.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ExpenseApplicationUpsert) ClearCreatedBy() *ExpenseApplicationUpsert {
	u.SetNull(expenseapplication.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ExpenseApplicationUpsert) SetUpdatedBy(v uint32) *ExpenseApplicationUpsert {
	u.Set(expenseapplication.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ExpenseApplicationUpsert) UpdateUpdatedBy() *ExpenseApplicationUpsert {
	u.SetExcluded(expenseapplication.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ExpenseApplicationUpsert) AddUpdatedBy(v uint32) *ExpenseApplicationUpsert {
	u.Add(expenseapplication.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ExpenseApplicationUpsert) ClearUpdatedBy() *ExpenseApplicationUpsert {
	u.SetNull(expenseapplication.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ExpenseApplicationUpsert) SetDeletedBy(v uint32) *ExpenseApplicationUpsert {
	u.Set(expenseapplication.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ExpenseApplicationUpsert) UpdateDeletedBy() *ExpenseApplicationUpsert {
	u.SetExcluded(expenseapplication.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ExpenseApplicationUpsert) AddDeletedBy(v uint32) *ExpenseApplicationUpsert {
	u.Add(expenseapplication.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ExpenseApplicationUpsert) ClearDeletedBy() *ExpenseApplicationUpsert {
	u.SetNull(expenseapplication.FieldDeletedBy)
	return u
}

// SetTitle sets the "title" field.
func (u *ExpenseApplicationUpsert) SetTitle(v string) *ExpenseApplicationUpsert {
	u.Set(expenseapplication.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ExpenseApplicationUpsert) UpdateTitle() *ExpenseApplicationUpsert {
	u.SetExcluded(expenseapplication.FieldTitle)
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *ExpenseApplicationUpsert) SetTotalAmount(v float64) *ExpenseApplicationUpsert {
	u.Set(expenseapplication.FieldTotalAmount, v)
	return u
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *ExpenseApplicationUpsert) UpdateTotalAmount() *ExpenseApplicationUpsert {
	u.SetExcluded(expenseapplication.FieldTotalAmount)
	return u
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *ExpenseApplicationUpsert) AddTotalAmount(v float64) *ExpenseApplicationUpsert {
	u.Add(expenseapplication.FieldTotalAmount, v)
	return u
}

// SetExpenseStatus sets the "expense_status" field.
func (u *ExpenseApplicationUpsert) SetExpenseStatus(v expenseapplication.ExpenseStatus) *ExpenseApplicationUpsert {
	u.Set(expenseapplication.FieldExpenseStatus, v)
	return u
}

// UpdateExpenseStatus sets the "expense_status" field to the value that was provided on create.
func (u *ExpenseApplicationUpsert) UpdateExpenseStatus() *ExpenseApplicationUpsert {
	u.SetExcluded(expenseapplication.FieldExpenseStatus)
	return u
}

// ClearExpenseStatus clears the value of the "expense_status" field.
func (u *ExpenseApplicationUpsert) ClearExpenseStatus() *ExpenseApplicationUpsert {
	u.SetNull(expenseapplication.FieldExpenseStatus)
	return u
}

// SetInstanceID sets the "instance_id" field.
func (u *ExpenseApplicationUpsert) SetInstanceID(v uint32) *ExpenseApplicationUpsert {
	u.Set(expenseapplication.FieldInstanceID, v)
	return u
}

// UpdateInstanceID sets the "instance_id" field to the value that was provided on create.
func (u *ExpenseApplicationUpsert) UpdateInstanceID() *ExpenseApplicationUpsert {
	u.SetExcluded(expenseapplication.FieldInstanceID)
	return u
}

// AddInstanceID adds v to the "instance_id" field.
func (u *ExpenseApplicationUpsert) AddInstanceID(v uint32) *ExpenseApplicationUpsert {
	u.Add(expenseapplication.FieldInstanceID, v)
	return u
}

// ClearInstanceID clears the value of the "instance_id" field.
func (u *ExpenseApplicationUpsert) ClearInstanceID() *ExpenseApplicationUpsert {
	u.SetNull(expenseapplication.FieldInstanceID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ExpenseApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(expenseapplication.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExpenseApplicationUpsertOne) UpdateNewValues() *ExpenseApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(expenseapplication.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(expenseapplication.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(expenseapplication.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExpenseApplication.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExpenseApplicationUpsertOne) Ignore() *ExpenseApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExpenseApplicationUpsertOne) DoNothing() *ExpenseApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExpenseApplicationCreate.OnConflict
// documentation for more info.
func (u *ExpenseApplicationUpsertOne) Update(set func(*ExpenseApplicationUpsert)) *ExpenseApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExpenseApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExpenseApplicationUpsertOne) SetUpdatedAt(v time.Time) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertOne) UpdateUpdatedAt() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ExpenseApplicationUpsertOne) ClearUpdatedAt() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ExpenseApplicationUpsertOne) SetDeletedAt(v time.Time) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertOne) UpdateDeletedAt() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ExpenseApplicationUpsertOne) ClearDeletedAt() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ExpenseApplicationUpsertOne) SetCreatedBy(v uint32) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ExpenseApplicationUpsertOne) AddCreatedBy(v uint32) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertOne) UpdateCreatedBy() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ExpenseApplicationUpsertOne) ClearCreatedBy() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ExpenseApplicationUpsertOne) SetUpdatedBy(v uint32) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ExpenseApplicationUpsertOne) AddUpdatedBy(v uint32) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertOne) UpdateUpdatedBy() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ExpenseApplicationUpsertOne) ClearUpdatedBy() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ExpenseApplicationUpsertOne) SetDeletedBy(v uint32) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ExpenseApplicationUpsertOne) AddDeletedBy(v uint32) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertOne) UpdateDeletedBy() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ExpenseApplicationUpsertOne) ClearDeletedBy() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearDeletedBy()
	})
}

// SetTitle sets the "title" field.
func (u *ExpenseApplicationUpsertOne) SetTitle(v string) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertOne) UpdateTitle() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateTitle()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *ExpenseApplicationUpsertOne) SetTotalAmount(v float64) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *ExpenseApplicationUpsertOne) AddTotalAmount(v float64) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertOne) UpdateTotalAmount() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetExpenseStatus sets the "expense_status" field.
func (u *ExpenseApplicationUpsertOne) SetExpenseStatus(v expenseapplication.ExpenseStatus) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetExpenseStatus(v)
	})
}

// UpdateExpenseStatus sets the "expense_status" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertOne) UpdateExpenseStatus() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateExpenseStatus()
	})
}

// ClearExpenseStatus clears the value of the "expense_status" field.
func (u *ExpenseApplicationUpsertOne) ClearExpenseStatus() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearExpenseStatus()
	})
}

// SetInstanceID sets the "instance_id" field.
func (u *ExpenseApplicationUpsertOne) SetInstanceID(v uint32) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetInstanceID(v)
	})
}

// AddInstanceID adds v to the "instance_id" field.
func (u *ExpenseApplicationUpsertOne) AddInstanceID(v uint32) *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.AddInstanceID(v)
	})
}

// UpdateInstanceID sets the "instance_id" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertOne) UpdateInstanceID() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateInstanceID()
	})
}

// ClearInstanceID clears the value of the "instance_id" field.
func (u *ExpenseApplicationUpsertOne) ClearInstanceID() *ExpenseApplicationUpsertOne {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearInstanceID()
	})
}

// Exec executes the query.
func (u *ExpenseApplicationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExpenseApplicationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExpenseApplicationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExpenseApplicationUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExpenseApplicationUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExpenseApplicationCreateBulk is the builder for creating many ExpenseApplication entities in bulk.
type ExpenseApplicationCreateBulk struct {
	config
	err      error
	builders []*ExpenseApplicationCreate
	conflict []sql.ConflictOption
}

// Save creates the ExpenseApplication entities in the database.
func (_c *ExpenseApplicationCreateBulk) Save(ctx context.Context) ([]*ExpenseApplication, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExpenseApplication, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExpenseApplicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExpenseApplicationCreateBulk) SaveX(ctx context.Context) []*ExpenseApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExpenseApplicationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExpenseApplicationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExpenseApplication.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExpenseApplicationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExpenseApplicationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExpenseApplicationUpsertBulk {
	_c.conflict = opts
	return &ExpenseApplicationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExpenseApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExpenseApplicationCreateBulk) OnConflictColumns(columns ...string) *ExpenseApplicationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExpenseApplicationUpsertBulk{
		create: _c,
	}
}

// ExpenseApplicationUpsertBulk is the builder for "upsert"-ing
// a bulk of ExpenseApplication nodes.
type ExpenseApplicationUpsertBulk struct {
	create *ExpenseApplicationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExpenseApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(expenseapplication.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExpenseApplicationUpsertBulk) UpdateNewValues() *ExpenseApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(expenseapplication.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(expenseapplication.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(expenseapplication.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExpenseApplication.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExpenseApplicationUpsertBulk) Ignore() *ExpenseApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExpenseApplicationUpsertBulk) DoNothing() *ExpenseApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExpenseApplicationCreateBulk.OnConflict
// documentation for more info.
func (u *ExpenseApplicationUpsertBulk) Update(set func(*ExpenseApplicationUpsert)) *ExpenseApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExpenseApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExpenseApplicationUpsertBulk) SetUpdatedAt(v time.Time) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertBulk) UpdateUpdatedAt() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *ExpenseApplicationUpsertBulk) ClearUpdatedAt() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ExpenseApplicationUpsertBulk) SetDeletedAt(v time.Time) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertBulk) UpdateDeletedAt() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ExpenseApplicationUpsertBulk) ClearDeletedAt() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ExpenseApplicationUpsertBulk) SetCreatedBy(v uint32) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ExpenseApplicationUpsertBulk) AddCreatedBy(v uint32) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertBulk) UpdateCreatedBy() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *ExpenseApplicationUpsertBulk) ClearCreatedBy() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ExpenseApplicationUpsertBulk) SetUpdatedBy(v uint32) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ExpenseApplicationUpsertBulk) AddUpdatedBy(v uint32) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertBulk) UpdateUpdatedBy() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ExpenseApplicationUpsertBulk) ClearUpdatedBy() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *ExpenseApplicationUpsertBulk) SetDeletedBy(v uint32) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *ExpenseApplicationUpsertBulk) AddDeletedBy(v uint32) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertBulk) UpdateDeletedBy() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *ExpenseApplicationUpsertBulk) ClearDeletedBy() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearDeletedBy()
	})
}

// SetTitle sets the "title" field.
func (u *ExpenseApplicationUpsertBulk) SetTitle(v string) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertBulk) UpdateTitle() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateTitle()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *ExpenseApplicationUpsertBulk) SetTotalAmount(v float64) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *ExpenseApplicationUpsertBulk) AddTotalAmount(v float64) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertBulk) UpdateTotalAmount() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetExpenseStatus sets the "expense_status" field.
func (u *ExpenseApplicationUpsertBulk) SetExpenseStatus(v expenseapplication.ExpenseStatus) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetExpenseStatus(v)
	})
}

// UpdateExpenseStatus sets the "expense_status" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertBulk) UpdateExpenseStatus() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateExpenseStatus()
	})
}

// ClearExpenseStatus clears the value of the "expense_status" field.
func (u *ExpenseApplicationUpsertBulk) ClearExpenseStatus() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearExpenseStatus()
	})
}

// SetInstanceID sets the "instance_id" field.
func (u *ExpenseApplicationUpsertBulk) SetInstanceID(v uint32) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.SetInstanceID(v)
	})
}

// AddInstanceID adds v to the "instance_id" field.
func (u *ExpenseApplicationUpsertBulk) AddInstanceID(v uint32) *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.AddInstanceID(v)
	})
}

// UpdateInstanceID sets the "instance_id" field to the value that was provided on create.
func (u *ExpenseApplicationUpsertBulk) UpdateInstanceID() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.UpdateInstanceID()
	})
}

// ClearInstanceID clears the value of the "instance_id" field.
func (u *ExpenseApplicationUpsertBulk) ClearInstanceID() *ExpenseApplicationUpsertBulk {
	return u.Update(func(s *ExpenseApplicationUpsert) {
		s.ClearInstanceID()
	})
}

// Exec executes the query.
func (u *ExpenseApplicationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExpenseApplicationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExpenseApplicationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExpenseApplicationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
