// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-wind-oa/app/core/service/internal/data/ent/overtimeapplication"
	"go-wind-oa/app/core/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OvertimeApplicationDelete is the builder for deleting a OvertimeApplication entity.
type OvertimeApplicationDelete struct {
	config
	hooks    []Hook
	mutation *OvertimeApplicationMutation
}

// Where appends a list predicates to the OvertimeApplicationDelete builder.
func (_d *OvertimeApplicationDelete) Where(ps ...predicate.OvertimeApplication) *OvertimeApplicationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OvertimeApplicationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OvertimeApplicationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OvertimeApplicationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(overtimeapplication.Table, sqlgraph.NewFieldSpec(overtimeapplication.FieldID, field.TypeUint32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OvertimeApplicationDeleteOne is the builder for deleting a single OvertimeApplication entity.
type OvertimeApplicationDeleteOne struct {
	_d *OvertimeApplicationDelete
}

// Where appends a list predicates to the OvertimeApplicationDelete builder.
func (_d *OvertimeApplicationDeleteOne) Where(ps ...predicate.OvertimeApplication) *OvertimeApplicationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OvertimeApplicationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{overtimeapplication.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OvertimeApplicationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
