// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-oa/app/core/service/internal/data/ent/predicate"
	"go-wind-oa/app/core/service/internal/data/ent/sitesetting"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SiteSettingUpdate is the builder for updating SiteSetting entities.
type SiteSettingUpdate struct {
	config
	hooks     []Hook
	mutation  *SiteSettingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SiteSettingUpdate builder.
func (_u *SiteSettingUpdate) Where(ps ...predicate.SiteSetting) *SiteSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteSettingUpdate) SetUpdatedAt(v time.Time) *SiteSettingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableUpdatedAt(v *time.Time) *SiteSettingUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SiteSettingUpdate) ClearUpdatedAt() *SiteSettingUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SiteSettingUpdate) SetDeletedAt(v time.Time) *SiteSettingUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableDeletedAt(v *time.Time) *SiteSettingUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SiteSettingUpdate) ClearDeletedAt() *SiteSettingUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SiteSettingUpdate) SetCreatedBy(v uint32) *SiteSettingUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableCreatedBy(v *uint32) *SiteSettingUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SiteSettingUpdate) AddCreatedBy(v int32) *SiteSettingUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SiteSettingUpdate) ClearCreatedBy() *SiteSettingUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SiteSettingUpdate) SetUpdatedBy(v uint32) *SiteSettingUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableUpdatedBy(v *uint32) *SiteSettingUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SiteSettingUpdate) AddUpdatedBy(v int32) *SiteSettingUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SiteSettingUpdate) ClearUpdatedBy() *SiteSettingUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SiteSettingUpdate) SetDeletedBy(v uint32) *SiteSettingUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableDeletedBy(v *uint32) *SiteSettingUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *SiteSettingUpdate) AddDeletedBy(v int32) *SiteSettingUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SiteSettingUpdate) ClearDeletedBy() *SiteSettingUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSiteID sets the "site_id" field.
func (_u *SiteSettingUpdate) SetSiteID(v uint32) *SiteSettingUpdate {
	_u.mutation.ResetSiteID()
	_u.mutation.SetSiteID(v)
	return _u
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableSiteID(v *uint32) *SiteSettingUpdate {
	if v != nil {
		_u.SetSiteID(*v)
	}
	return _u
}

// AddSiteID adds value to the "site_id" field.
func (_u *SiteSettingUpdate) AddSiteID(v int32) *SiteSettingUpdate {
	_u.mutation.AddSiteID(v)
	return _u
}

// ClearSiteID clears the value of the "site_id" field.
func (_u *SiteSettingUpdate) ClearSiteID() *SiteSettingUpdate {
	_u.mutation.ClearSiteID()
	return _u
}

// SetLocale sets the "locale" field.
func (_u *SiteSettingUpdate) SetLocale(v string) *SiteSettingUpdate {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableLocale(v *string) *SiteSettingUpdate {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// ClearLocale clears the value of the "locale" field.
func (_u *SiteSettingUpdate) ClearLocale() *SiteSettingUpdate {
	_u.mutation.ClearLocale()
	return _u
}

// SetGroup sets the "group" field.
func (_u *SiteSettingUpdate) SetGroup(v string) *SiteSettingUpdate {
	_u.mutation.SetGroup(v)
	return _u
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableGroup(v *string) *SiteSettingUpdate {
	if v != nil {
		_u.SetGroup(*v)
	}
	return _u
}

// ClearGroup clears the value of the "group" field.
func (_u *SiteSettingUpdate) ClearGroup() *SiteSettingUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// SetKey sets the "key" field.
func (_u *SiteSettingUpdate) SetKey(v string) *SiteSettingUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableKey(v *string) *SiteSettingUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// ClearKey clears the value of the "key" field.
func (_u *SiteSettingUpdate) ClearKey() *SiteSettingUpdate {
	_u.mutation.ClearKey()
	return _u
}

// SetValue sets the "value" field.
func (_u *SiteSettingUpdate) SetValue(v string) *SiteSettingUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableValue(v *string) *SiteSettingUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *SiteSettingUpdate) ClearValue() *SiteSettingUpdate {
	_u.mutation.ClearValue()
	return _u
}

// SetType sets the "type" field.
func (_u *SiteSettingUpdate) SetType(v sitesetting.Type) *SiteSettingUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableType(v *sitesetting.Type) *SiteSettingUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *SiteSettingUpdate) ClearType() *SiteSettingUpdate {
	_u.mutation.ClearType()
	return _u
}

// SetLabel sets the "label" field.
func (_u *SiteSettingUpdate) SetLabel(v string) *SiteSettingUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableLabel(v *string) *SiteSettingUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *SiteSettingUpdate) ClearLabel() *SiteSettingUpdate {
	_u.mutation.ClearLabel()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SiteSettingUpdate) SetDescription(v string) *SiteSettingUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableDescription(v *string) *SiteSettingUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SiteSettingUpdate) ClearDescription() *SiteSettingUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPlaceholder sets the "placeholder" field.
func (_u *SiteSettingUpdate) SetPlaceholder(v string) *SiteSettingUpdate {
	_u.mutation.SetPlaceholder(v)
	return _u
}

// SetNillablePlaceholder sets the "placeholder" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillablePlaceholder(v *string) *SiteSettingUpdate {
	if v != nil {
		_u.SetPlaceholder(*v)
	}
	return _u
}

// ClearPlaceholder clears the value of the "placeholder" field.
func (_u *SiteSettingUpdate) ClearPlaceholder() *SiteSettingUpdate {
	_u.mutation.ClearPlaceholder()
	return _u
}

// SetOptions sets the "options" field.
func (_u *SiteSettingUpdate) SetOptions(v *map[string]string) *SiteSettingUpdate {
	_u.mutation.SetOptions(v)
	return _u
}

// ClearOptions clears the value of the "options" field.
func (_u *SiteSettingUpdate) ClearOptions() *SiteSettingUpdate {
	_u.mutation.ClearOptions()
	return _u
}

// SetIsRequired sets the "is_required" field.
func (_u *SiteSettingUpdate) SetIsRequired(v bool) *SiteSettingUpdate {
	_u.mutation.SetIsRequired(v)
	return _u
}

// SetNillableIsRequired sets the "is_required" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableIsRequired(v *bool) *SiteSettingUpdate {
	if v != nil {
		_u.SetIsRequired(*v)
	}
	return _u
}

// ClearIsRequired clears the value of the "is_required" field.
func (_u *SiteSettingUpdate) ClearIsRequired() *SiteSettingUpdate {
	_u.mutation.ClearIsRequired()
	return _u
}

// SetValidationRegex sets the "validation_regex" field.
func (_u *SiteSettingUpdate) SetValidationRegex(v string) *SiteSettingUpdate {
	_u.mutation.SetValidationRegex(v)
	return _u
}

// SetNillableValidationRegex sets the "validation_regex" field if the given value is not nil.
func (_u *SiteSettingUpdate) SetNillableValidationRegex(v *string) *SiteSettingUpdate {
	if v != nil {
		_u.SetValidationRegex(*v)
	}
	return _u
}

// ClearValidationRegex clears the value of the "validation_regex" field.
func (_u *SiteSettingUpdate) ClearValidationRegex() *SiteSettingUpdate {
	_u.mutation.ClearValidationRegex()
	return _u
}

// Mutation returns the SiteSettingMutation object of the builder.
func (_u *SiteSettingUpdate) Mutation() *SiteSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SiteSettingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SiteSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SiteSettingUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := sitesetting.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SiteSetting.type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SiteSettingUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SiteSettingUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SiteSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sitesetting.Table, sitesetting.Columns, sqlgraph.NewFieldSpec(sitesetting.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(sitesetting.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sitesetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(sitesetting.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sitesetting.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sitesetting.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(sitesetting.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(sitesetting.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(sitesetting.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sitesetting.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(sitesetting.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(sitesetting.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(sitesetting.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(sitesetting.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(sitesetting.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(sitesetting.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.SiteID(); ok {
		_spec.SetField(sitesetting.FieldSiteID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSiteID(); ok {
		_spec.AddField(sitesetting.FieldSiteID, field.TypeUint32, value)
	}
	if _u.mutation.SiteIDCleared() {
		_spec.ClearField(sitesetting.FieldSiteID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(sitesetting.FieldLocale, field.TypeString, value)
	}
	if _u.mutation.LocaleCleared() {
		_spec.ClearField(sitesetting.FieldLocale, field.TypeString)
	}
	if value, ok := _u.mutation.Group(); ok {
		_spec.SetField(sitesetting.FieldGroup, field.TypeString, value)
	}
	if _u.mutation.GroupCleared() {
		_spec.ClearField(sitesetting.FieldGroup, field.TypeString)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(sitesetting.FieldKey, field.TypeString, value)
	}
	if _u.mutation.KeyCleared() {
		_spec.ClearField(sitesetting.FieldKey, field.TypeString)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(sitesetting.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(sitesetting.FieldValue, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(sitesetting.FieldType, field.TypeEnum, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(sitesetting.FieldType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(sitesetting.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(sitesetting.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(sitesetting.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(sitesetting.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Placeholder(); ok {
		_spec.SetField(sitesetting.FieldPlaceholder, field.TypeString, value)
	}
	if _u.mutation.PlaceholderCleared() {
		_spec.ClearField(sitesetting.FieldPlaceholder, field.TypeString)
	}
	if value, ok := _u.mutation.Options(); ok {
		_spec.SetField(sitesetting.FieldOptions, field.TypeJSON, value)
	}
	if _u.mutation.OptionsCleared() {
		_spec.ClearField(sitesetting.FieldOptions, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsRequired(); ok {
		_spec.SetField(sitesetting.FieldIsRequired, field.TypeBool, value)
	}
	if _u.mutation.IsRequiredCleared() {
		_spec.ClearField(sitesetting.FieldIsRequired, field.TypeBool)
	}
	if value, ok := _u.mutation.ValidationRegex(); ok {
		_spec.SetField(sitesetting.FieldValidationRegex, field.TypeString, value)
	}
	if _u.mutation.ValidationRegexCleared() {
		_spec.ClearField(sitesetting.FieldValidationRegex, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sitesetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SiteSettingUpdateOne is the builder for updating a single SiteSetting entity.
type SiteSettingUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SiteSettingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteSettingUpdateOne) SetUpdatedAt(v time.Time) *SiteSettingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableUpdatedAt(v *time.Time) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SiteSettingUpdateOne) ClearUpdatedAt() *SiteSettingUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SiteSettingUpdateOne) SetDeletedAt(v time.Time) *SiteSettingUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableDeletedAt(v *time.Time) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SiteSettingUpdateOne) ClearDeletedAt() *SiteSettingUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SiteSettingUpdateOne) SetCreatedBy(v uint32) *SiteSettingUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableCreatedBy(v *uint32) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SiteSettingUpdateOne) AddCreatedBy(v int32) *SiteSettingUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SiteSettingUpdateOne) ClearCreatedBy() *SiteSettingUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SiteSettingUpdateOne) SetUpdatedBy(v uint32) *SiteSettingUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableUpdatedBy(v *uint32) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SiteSettingUpdateOne) AddUpdatedBy(v int32) *SiteSettingUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SiteSettingUpdateOne) ClearUpdatedBy() *SiteSettingUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SiteSettingUpdateOne) SetDeletedBy(v uint32) *SiteSettingUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableDeletedBy(v *uint32) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *SiteSettingUpdateOne) AddDeletedBy(v int32) *SiteSettingUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SiteSettingUpdateOne) ClearDeletedBy() *SiteSettingUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSiteID sets the "site_id" field.
func (_u *SiteSettingUpdateOne) SetSiteID(v uint32) *SiteSettingUpdateOne {
	_u.mutation.ResetSiteID()
	_u.mutation.SetSiteID(v)
	return _u
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableSiteID(v *uint32) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetSiteID(*v)
	}
	return _u
}

// AddSiteID adds value to the "site_id" field.
func (_u *SiteSettingUpdateOne) AddSiteID(v int32) *SiteSettingUpdateOne {
	_u.mutation.AddSiteID(v)
	return _u
}

// ClearSiteID clears the value of the "site_id" field.
func (_u *SiteSettingUpdateOne) ClearSiteID() *SiteSettingUpdateOne {
	_u.mutation.ClearSiteID()
	return _u
}

// SetLocale sets the "locale" field.
func (_u *SiteSettingUpdateOne) SetLocale(v string) *SiteSettingUpdateOne {
	_u.mutation.SetLocale(v)
	return _u
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableLocale(v *string) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetLocale(*v)
	}
	return _u
}

// ClearLocale clears the value of the "locale" field.
func (_u *SiteSettingUpdateOne) ClearLocale() *SiteSettingUpdateOne {
	_u.mutation.ClearLocale()
	return _u
}

// SetGroup sets the "group" field.
func (_u *SiteSettingUpdateOne) SetGroup(v string) *SiteSettingUpdateOne {
	_u.mutation.SetGroup(v)
	return _u
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableGroup(v *string) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetGroup(*v)
	}
	return _u
}

// ClearGroup clears the value of the "group" field.
func (_u *SiteSettingUpdateOne) ClearGroup() *SiteSettingUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// SetKey sets the "key" field.
func (_u *SiteSettingUpdateOne) SetKey(v string) *SiteSettingUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableKey(v *string) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// ClearKey clears the value of the "key" field.
func (_u *SiteSettingUpdateOne) ClearKey() *SiteSettingUpdateOne {
	_u.mutation.ClearKey()
	return _u
}

// SetValue sets the "value" field.
func (_u *SiteSettingUpdateOne) SetValue(v string) *SiteSettingUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableValue(v *string) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *SiteSettingUpdateOne) ClearValue() *SiteSettingUpdateOne {
	_u.mutation.ClearValue()
	return _u
}

// SetType sets the "type" field.
func (_u *SiteSettingUpdateOne) SetType(v sitesetting.Type) *SiteSettingUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableType(v *sitesetting.Type) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *SiteSettingUpdateOne) ClearType() *SiteSettingUpdateOne {
	_u.mutation.ClearType()
	return _u
}

// SetLabel sets the "label" field.
func (_u *SiteSettingUpdateOne) SetLabel(v string) *SiteSettingUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableLabel(v *string) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *SiteSettingUpdateOne) ClearLabel() *SiteSettingUpdateOne {
	_u.mutation.ClearLabel()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SiteSettingUpdateOne) SetDescription(v string) *SiteSettingUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableDescription(v *string) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SiteSettingUpdateOne) ClearDescription() *SiteSettingUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPlaceholder sets the "placeholder" field.
func (_u *SiteSettingUpdateOne) SetPlaceholder(v string) *SiteSettingUpdateOne {
	_u.mutation.SetPlaceholder(v)
	return _u
}

// SetNillablePlaceholder sets the "placeholder" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillablePlaceholder(v *string) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetPlaceholder(*v)
	}
	return _u
}

// ClearPlaceholder clears the value of the "placeholder" field.
func (_u *SiteSettingUpdateOne) ClearPlaceholder() *SiteSettingUpdateOne {
	_u.mutation.ClearPlaceholder()
	return _u
}

// SetOptions sets the "options" field.
func (_u *SiteSettingUpdateOne) SetOptions(v *map[string]string) *SiteSettingUpdateOne {
	_u.mutation.SetOptions(v)
	return _u
}

// ClearOptions clears the value of the "options" field.
func (_u *SiteSettingUpdateOne) ClearOptions() *SiteSettingUpdateOne {
	_u.mutation.ClearOptions()
	return _u
}

// SetIsRequired sets the "is_required" field.
func (_u *SiteSettingUpdateOne) SetIsRequired(v bool) *SiteSettingUpdateOne {
	_u.mutation.SetIsRequired(v)
	return _u
}

// SetNillableIsRequired sets the "is_required" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableIsRequired(v *bool) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetIsRequired(*v)
	}
	return _u
}

// ClearIsRequired clears the value of the "is_required" field.
func (_u *SiteSettingUpdateOne) ClearIsRequired() *SiteSettingUpdateOne {
	_u.mutation.ClearIsRequired()
	return _u
}

// SetValidationRegex sets the "validation_regex" field.
func (_u *SiteSettingUpdateOne) SetValidationRegex(v string) *SiteSettingUpdateOne {
	_u.mutation.SetValidationRegex(v)
	return _u
}

// SetNillableValidationRegex sets the "validation_regex" field if the given value is not nil.
func (_u *SiteSettingUpdateOne) SetNillableValidationRegex(v *string) *SiteSettingUpdateOne {
	if v != nil {
		_u.SetValidationRegex(*v)
	}
	return _u
}

// ClearValidationRegex clears the value of the "validation_regex" field.
func (_u *SiteSettingUpdateOne) ClearValidationRegex() *SiteSettingUpdateOne {
	_u.mutation.ClearValidationRegex()
	return _u
}

// Mutation returns the SiteSettingMutation object of the builder.
func (_u *SiteSettingUpdateOne) Mutation() *SiteSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the SiteSettingUpdate builder.
func (_u *SiteSettingUpdateOne) Where(ps ...predicate.SiteSetting) *SiteSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SiteSettingUpdateOne) Select(field string, fields ...string) *SiteSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SiteSetting entity.
func (_u *SiteSettingUpdateOne) Save(ctx context.Context) (*SiteSetting, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteSettingUpdateOne) SaveX(ctx context.Context) *SiteSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SiteSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SiteSettingUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := sitesetting.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SiteSetting.type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SiteSettingUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SiteSettingUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SiteSettingUpdateOne) sqlSave(ctx context.Context) (_node *SiteSetting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sitesetting.Table, sitesetting.Columns, sqlgraph.NewFieldSpec(sitesetting.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SiteSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sitesetting.FieldID)
		for _, f := range fields {
			if !sitesetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sitesetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(sitesetting.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sitesetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(sitesetting.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sitesetting.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sitesetting.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(sitesetting.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(sitesetting.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(sitesetting.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sitesetting.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(sitesetting.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(sitesetting.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(sitesetting.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(sitesetting.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(sitesetting.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(sitesetting.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.SiteID(); ok {
		_spec.SetField(sitesetting.FieldSiteID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSiteID(); ok {
		_spec.AddField(sitesetting.FieldSiteID, field.TypeUint32, value)
	}
	if _u.mutation.SiteIDCleared() {
		_spec.ClearField(sitesetting.FieldSiteID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Locale(); ok {
		_spec.SetField(sitesetting.FieldLocale, field.TypeString, value)
	}
	if _u.mutation.LocaleCleared() {
		_spec.ClearField(sitesetting.FieldLocale, field.TypeString)
	}
	if value, ok := _u.mutation.Group(); ok {
		_spec.SetField(sitesetting.FieldGroup, field.TypeString, value)
	}
	if _u.mutation.GroupCleared() {
		_spec.ClearField(sitesetting.FieldGroup, field.TypeString)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(sitesetting.FieldKey, field.TypeString, value)
	}
	if _u.mutation.KeyCleared() {
		_spec.ClearField(sitesetting.FieldKey, field.TypeString)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(sitesetting.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(sitesetting.FieldValue, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(sitesetting.FieldType, field.TypeEnum, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(sitesetting.FieldType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(sitesetting.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(sitesetting.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(sitesetting.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(sitesetting.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Placeholder(); ok {
		_spec.SetField(sitesetting.FieldPlaceholder, field.TypeString, value)
	}
	if _u.mutation.PlaceholderCleared() {
		_spec.ClearField(sitesetting.FieldPlaceholder, field.TypeString)
	}
	if value, ok := _u.mutation.Options(); ok {
		_spec.SetField(sitesetting.FieldOptions, field.TypeJSON, value)
	}
	if _u.mutation.OptionsCleared() {
		_spec.ClearField(sitesetting.FieldOptions, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsRequired(); ok {
		_spec.SetField(sitesetting.FieldIsRequired, field.TypeBool, value)
	}
	if _u.mutation.IsRequiredCleared() {
		_spec.ClearField(sitesetting.FieldIsRequired, field.TypeBool)
	}
	if value, ok := _u.mutation.ValidationRegex(); ok {
		_spec.SetField(sitesetting.FieldValidationRegex, field.TypeString, value)
	}
	if _u.mutation.ValidationRegexCleared() {
		_spec.ClearField(sitesetting.FieldValidationRegex, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SiteSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sitesetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
