// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-oa/app/core/service/internal/data/ent/predicate"
	"go-wind-oa/app/core/service/internal/data/ent/site"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// SiteUpdate is the builder for updating Site entities.
type SiteUpdate struct {
	config
	hooks     []Hook
	mutation  *SiteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SiteUpdate builder.
func (_u *SiteUpdate) Where(ps ...predicate.Site) *SiteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteUpdate) SetUpdatedAt(v time.Time) *SiteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableUpdatedAt(v *time.Time) *SiteUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SiteUpdate) ClearUpdatedAt() *SiteUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SiteUpdate) SetDeletedAt(v time.Time) *SiteUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableDeletedAt(v *time.Time) *SiteUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SiteUpdate) ClearDeletedAt() *SiteUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SiteUpdate) SetCreatedBy(v uint32) *SiteUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableCreatedBy(v *uint32) *SiteUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SiteUpdate) AddCreatedBy(v int32) *SiteUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SiteUpdate) ClearCreatedBy() *SiteUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SiteUpdate) SetUpdatedBy(v uint32) *SiteUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableUpdatedBy(v *uint32) *SiteUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SiteUpdate) AddUpdatedBy(v int32) *SiteUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SiteUpdate) ClearUpdatedBy() *SiteUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SiteUpdate) SetDeletedBy(v uint32) *SiteUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableDeletedBy(v *uint32) *SiteUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *SiteUpdate) AddDeletedBy(v int32) *SiteUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SiteUpdate) ClearDeletedBy() *SiteUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *SiteUpdate) SetName(v string) *SiteUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableName(v *string) *SiteUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *SiteUpdate) ClearName() *SiteUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetSlug sets the "slug" field.
func (_u *SiteUpdate) SetSlug(v string) *SiteUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableSlug(v *string) *SiteUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *SiteUpdate) ClearSlug() *SiteUpdate {
	_u.mutation.ClearSlug()
	return _u
}

// SetDomain sets the "domain" field.
func (_u *SiteUpdate) SetDomain(v string) *SiteUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableDomain(v *string) *SiteUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *SiteUpdate) ClearDomain() *SiteUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// SetAlternateDomains sets the "alternate_domains" field.
func (_u *SiteUpdate) SetAlternateDomains(v []string) *SiteUpdate {
	_u.mutation.SetAlternateDomains(v)
	return _u
}

// AppendAlternateDomains appends value to the "alternate_domains" field.
func (_u *SiteUpdate) AppendAlternateDomains(v []string) *SiteUpdate {
	_u.mutation.AppendAlternateDomains(v)
	return _u
}

// ClearAlternateDomains clears the value of the "alternate_domains" field.
func (_u *SiteUpdate) ClearAlternateDomains() *SiteUpdate {
	_u.mutation.ClearAlternateDomains()
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *SiteUpdate) SetIsDefault(v bool) *SiteUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableIsDefault(v *bool) *SiteUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// ClearIsDefault clears the value of the "is_default" field.
func (_u *SiteUpdate) ClearIsDefault() *SiteUpdate {
	_u.mutation.ClearIsDefault()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SiteUpdate) SetStatus(v site.Status) *SiteUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableStatus(v *site.Status) *SiteUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *SiteUpdate) ClearStatus() *SiteUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetDefaultLocale sets the "default_locale" field.
func (_u *SiteUpdate) SetDefaultLocale(v string) *SiteUpdate {
	_u.mutation.SetDefaultLocale(v)
	return _u
}

// SetNillableDefaultLocale sets the "default_locale" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableDefaultLocale(v *string) *SiteUpdate {
	if v != nil {
		_u.SetDefaultLocale(*v)
	}
	return _u
}

// ClearDefaultLocale clears the value of the "default_locale" field.
func (_u *SiteUpdate) ClearDefaultLocale() *SiteUpdate {
	_u.mutation.ClearDefaultLocale()
	return _u
}

// SetTemplate sets the "template" field.
func (_u *SiteUpdate) SetTemplate(v string) *SiteUpdate {
	_u.mutation.SetTemplate(v)
	return _u
}

// SetNillableTemplate sets the "template" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableTemplate(v *string) *SiteUpdate {
	if v != nil {
		_u.SetTemplate(*v)
	}
	return _u
}

// ClearTemplate clears the value of the "template" field.
func (_u *SiteUpdate) ClearTemplate() *SiteUpdate {
	_u.mutation.ClearTemplate()
	return _u
}

// SetTheme sets the "theme" field.
func (_u *SiteUpdate) SetTheme(v string) *SiteUpdate {
	_u.mutation.SetTheme(v)
	return _u
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableTheme(v *string) *SiteUpdate {
	if v != nil {
		_u.SetTheme(*v)
	}
	return _u
}

// ClearTheme clears the value of the "theme" field.
func (_u *SiteUpdate) ClearTheme() *SiteUpdate {
	_u.mutation.ClearTheme()
	return _u
}

// Mutation returns the SiteMutation object of the builder.
func (_u *SiteUpdate) Mutation() *SiteMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SiteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SiteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SiteUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := site.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Site.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SiteUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SiteUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SiteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(site.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(site.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(site.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(site.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(site.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(site.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(site.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(site.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(site.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(site.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(site.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(site.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(site.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(site.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(site.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(site.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(site.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(site.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(site.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(site.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.AlternateDomains(); ok {
		_spec.SetField(site.FieldAlternateDomains, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAlternateDomains(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, site.FieldAlternateDomains, value)
		})
	}
	if _u.mutation.AlternateDomainsCleared() {
		_spec.ClearField(site.FieldAlternateDomains, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(site.FieldIsDefault, field.TypeBool, value)
	}
	if _u.mutation.IsDefaultCleared() {
		_spec.ClearField(site.FieldIsDefault, field.TypeBool)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(site.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(site.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.DefaultLocale(); ok {
		_spec.SetField(site.FieldDefaultLocale, field.TypeString, value)
	}
	if _u.mutation.DefaultLocaleCleared() {
		_spec.ClearField(site.FieldDefaultLocale, field.TypeString)
	}
	if value, ok := _u.mutation.Template(); ok {
		_spec.SetField(site.FieldTemplate, field.TypeString, value)
	}
	if _u.mutation.TemplateCleared() {
		_spec.ClearField(site.FieldTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.Theme(); ok {
		_spec.SetField(site.FieldTheme, field.TypeString, value)
	}
	if _u.mutation.ThemeCleared() {
		_spec.ClearField(site.FieldTheme, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SiteUpdateOne is the builder for updating a single Site entity.
type SiteUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SiteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteUpdateOne) SetUpdatedAt(v time.Time) *SiteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableUpdatedAt(v *time.Time) *SiteUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SiteUpdateOne) ClearUpdatedAt() *SiteUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SiteUpdateOne) SetDeletedAt(v time.Time) *SiteUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableDeletedAt(v *time.Time) *SiteUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SiteUpdateOne) ClearDeletedAt() *SiteUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SiteUpdateOne) SetCreatedBy(v uint32) *SiteUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableCreatedBy(v *uint32) *SiteUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SiteUpdateOne) AddCreatedBy(v int32) *SiteUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SiteUpdateOne) ClearCreatedBy() *SiteUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SiteUpdateOne) SetUpdatedBy(v uint32) *SiteUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableUpdatedBy(v *uint32) *SiteUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SiteUpdateOne) AddUpdatedBy(v int32) *SiteUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SiteUpdateOne) ClearUpdatedBy() *SiteUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SiteUpdateOne) SetDeletedBy(v uint32) *SiteUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableDeletedBy(v *uint32) *SiteUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *SiteUpdateOne) AddDeletedBy(v int32) *SiteUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SiteUpdateOne) ClearDeletedBy() *SiteUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetName sets the "name" field.
func (_u *SiteUpdateOne) SetName(v string) *SiteUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableName(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *SiteUpdateOne) ClearName() *SiteUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetSlug sets the "slug" field.
func (_u *SiteUpdateOne) SetSlug(v string) *SiteUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableSlug(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *SiteUpdateOne) ClearSlug() *SiteUpdateOne {
	_u.mutation.ClearSlug()
	return _u
}

// SetDomain sets the "domain" field.
func (_u *SiteUpdateOne) SetDomain(v string) *SiteUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableDomain(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *SiteUpdateOne) ClearDomain() *SiteUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// SetAlternateDomains sets the "alternate_domains" field.
func (_u *SiteUpdateOne) SetAlternateDomains(v []string) *SiteUpdateOne {
	_u.mutation.SetAlternateDomains(v)
	return _u
}

// AppendAlternateDomains appends value to the "alternate_domains" field.
func (_u *SiteUpdateOne) AppendAlternateDomains(v []string) *SiteUpdateOne {
	_u.mutation.AppendAlternateDomains(v)
	return _u
}

// ClearAlternateDomains clears the value of the "alternate_domains" field.
func (_u *SiteUpdateOne) ClearAlternateDomains() *SiteUpdateOne {
	_u.mutation.ClearAlternateDomains()
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *SiteUpdateOne) SetIsDefault(v bool) *SiteUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableIsDefault(v *bool) *SiteUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// ClearIsDefault clears the value of the "is_default" field.
func (_u *SiteUpdateOne) ClearIsDefault() *SiteUpdateOne {
	_u.mutation.ClearIsDefault()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SiteUpdateOne) SetStatus(v site.Status) *SiteUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableStatus(v *site.Status) *SiteUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *SiteUpdateOne) ClearStatus() *SiteUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetDefaultLocale sets the "default_locale" field.
func (_u *SiteUpdateOne) SetDefaultLocale(v string) *SiteUpdateOne {
	_u.mutation.SetDefaultLocale(v)
	return _u
}

// SetNillableDefaultLocale sets the "default_locale" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableDefaultLocale(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetDefaultLocale(*v)
	}
	return _u
}

// ClearDefaultLocale clears the value of the "default_locale" field.
func (_u *SiteUpdateOne) ClearDefaultLocale() *SiteUpdateOne {
	_u.mutation.ClearDefaultLocale()
	return _u
}

// SetTemplate sets the "template" field.
func (_u *SiteUpdateOne) SetTemplate(v string) *SiteUpdateOne {
	_u.mutation.SetTemplate(v)
	return _u
}

// SetNillableTemplate sets the "template" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableTemplate(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetTemplate(*v)
	}
	return _u
}

// ClearTemplate clears the value of the "template" field.
func (_u *SiteUpdateOne) ClearTemplate() *SiteUpdateOne {
	_u.mutation.ClearTemplate()
	return _u
}

// SetTheme sets the "theme" field.
func (_u *SiteUpdateOne) SetTheme(v string) *SiteUpdateOne {
	_u.mutation.SetTheme(v)
	return _u
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableTheme(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetTheme(*v)
	}
	return _u
}

// ClearTheme clears the value of the "theme" field.
func (_u *SiteUpdateOne) ClearTheme() *SiteUpdateOne {
	_u.mutation.ClearTheme()
	return _u
}

// Mutation returns the SiteMutation object of the builder.
func (_u *SiteUpdateOne) Mutation() *SiteMutation {
	return _u.mutation
}

// Where appends a list predicates to the SiteUpdate builder.
func (_u *SiteUpdateOne) Where(ps ...predicate.Site) *SiteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SiteUpdateOne) Select(field string, fields ...string) *SiteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Site entity.
func (_u *SiteUpdateOne) Save(ctx context.Context) (*Site, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteUpdateOne) SaveX(ctx context.Context) *Site {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SiteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SiteUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := site.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Site.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SiteUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SiteUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SiteUpdateOne) sqlSave(ctx context.Context) (_node *Site, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Site.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, site.FieldID)
		for _, f := range fields {
			if !site.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != site.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(site.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(site.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(site.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(site.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(site.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(site.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(site.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(site.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(site.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(site.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(site.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(site.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(site.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(site.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(site.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(site.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(site.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(site.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(site.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(site.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.AlternateDomains(); ok {
		_spec.SetField(site.FieldAlternateDomains, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAlternateDomains(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, site.FieldAlternateDomains, value)
		})
	}
	if _u.mutation.AlternateDomainsCleared() {
		_spec.ClearField(site.FieldAlternateDomains, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(site.FieldIsDefault, field.TypeBool, value)
	}
	if _u.mutation.IsDefaultCleared() {
		_spec.ClearField(site.FieldIsDefault, field.TypeBool)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(site.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(site.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.DefaultLocale(); ok {
		_spec.SetField(site.FieldDefaultLocale, field.TypeString, value)
	}
	if _u.mutation.DefaultLocaleCleared() {
		_spec.ClearField(site.FieldDefaultLocale, field.TypeString)
	}
	if value, ok := _u.mutation.Template(); ok {
		_spec.SetField(site.FieldTemplate, field.TypeString, value)
	}
	if _u.mutation.TemplateCleared() {
		_spec.ClearField(site.FieldTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.Theme(); ok {
		_spec.SetField(site.FieldTheme, field.TypeString, value)
	}
	if _u.mutation.ThemeCleared() {
		_spec.ClearField(site.FieldTheme, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Site{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
