// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-oa/app/core/service/internal/data/ent/predicate"
	"go-wind-oa/app/core/service/internal/data/ent/workflowinstance"
	"go-wind-oa/app/core/service/internal/data/ent/workflowinstancejoin"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkflowInstanceJoinQuery is the builder for querying WorkflowInstanceJoin entities.
type WorkflowInstanceJoinQuery struct {
	config
	ctx          *QueryContext
	order        []workflowinstancejoin.OrderOption
	inters       []Interceptor
	predicates   []predicate.WorkflowInstanceJoin
	withInstance *WorkflowInstanceQuery
	withFKs      bool
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WorkflowInstanceJoinQuery builder.
func (_q *WorkflowInstanceJoinQuery) Where(ps ...predicate.WorkflowInstanceJoin) *WorkflowInstanceJoinQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *WorkflowInstanceJoinQuery) Limit(limit int) *WorkflowInstanceJoinQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *WorkflowInstanceJoinQuery) Offset(offset int) *WorkflowInstanceJoinQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *WorkflowInstanceJoinQuery) Unique(unique bool) *WorkflowInstanceJoinQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *WorkflowInstanceJoinQuery) Order(o ...workflowinstancejoin.OrderOption) *WorkflowInstanceJoinQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryInstance chains the current query on the "instance" edge.
func (_q *WorkflowInstanceJoinQuery) QueryInstance() *WorkflowInstanceQuery {
	query := (&WorkflowInstanceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workflowinstancejoin.Table, workflowinstancejoin.FieldID, selector),
			sqlgraph.To(workflowinstance.Table, workflowinstance.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, workflowinstancejoin.InstanceTable, workflowinstancejoin.InstanceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WorkflowInstanceJoin entity from the query.
// Returns a *NotFoundError when no WorkflowInstanceJoin was found.
func (_q *WorkflowInstanceJoinQuery) First(ctx context.Context) (*WorkflowInstanceJoin, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{workflowinstancejoin.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *WorkflowInstanceJoinQuery) FirstX(ctx context.Context) *WorkflowInstanceJoin {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WorkflowInstanceJoin ID from the query.
// Returns a *NotFoundError when no WorkflowInstanceJoin ID was found.
func (_q *WorkflowInstanceJoinQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{workflowinstancejoin.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *WorkflowInstanceJoinQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WorkflowInstanceJoin entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WorkflowInstanceJoin entity is found.
// Returns a *NotFoundError when no WorkflowInstanceJoin entities are found.
func (_q *WorkflowInstanceJoinQuery) Only(ctx context.Context) (*WorkflowInstanceJoin, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{workflowinstancejoin.Label}
	default:
		return nil, &NotSingularError{workflowinstancejoin.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *WorkflowInstanceJoinQuery) OnlyX(ctx context.Context) *WorkflowInstanceJoin {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WorkflowInstanceJoin ID in the query.
// Returns a *NotSingularError when more than one WorkflowInstanceJoin ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *WorkflowInstanceJoinQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{workflowinstancejoin.Label}
	default:
		err = &NotSingularError{workflowinstancejoin.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *WorkflowInstanceJoinQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WorkflowInstanceJoins.
func (_q *WorkflowInstanceJoinQuery) All(ctx context.Context) ([]*WorkflowInstanceJoin, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WorkflowInstanceJoin, *WorkflowInstanceJoinQuery]()
	return withInterceptors[[]*WorkflowInstanceJoin](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *WorkflowInstanceJoinQuery) AllX(ctx context.Context) []*WorkflowInstanceJoin {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WorkflowInstanceJoin IDs.
func (_q *WorkflowInstanceJoinQuery) IDs(ctx context.Context) (ids []uint32, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(workflowinstancejoin.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *WorkflowInstanceJoinQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *WorkflowInstanceJoinQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*WorkflowInstanceJoinQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *WorkflowInstanceJoinQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *WorkflowInstanceJoinQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *WorkflowInstanceJoinQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WorkflowInstanceJoinQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *WorkflowInstanceJoinQuery) Clone() *WorkflowInstanceJoinQuery {
	if _q == nil {
		return nil
	}
	return &WorkflowInstanceJoinQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]workflowinstancejoin.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.WorkflowInstanceJoin{}, _q.predicates...),
		withInstance: _q.withInstance.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithInstance tells the query-builder to eager-load the nodes that are connected to
// the "instance" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkflowInstanceJoinQuery) WithInstance(opts ...func(*WorkflowInstanceQuery)) *WorkflowInstanceJoinQuery {
	query := (&WorkflowInstanceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInstance = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WorkflowInstanceJoin.Query().
//		GroupBy(workflowinstancejoin.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *WorkflowInstanceJoinQuery) GroupBy(field string, fields ...string) *WorkflowInstanceJoinGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WorkflowInstanceJoinGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = workflowinstancejoin.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.WorkflowInstanceJoin.Query().
//		Select(workflowinstancejoin.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *WorkflowInstanceJoinQuery) Select(fields ...string) *WorkflowInstanceJoinSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &WorkflowInstanceJoinSelect{WorkflowInstanceJoinQuery: _q}
	sbuild.label = workflowinstancejoin.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WorkflowInstanceJoinSelect configured with the given aggregations.
func (_q *WorkflowInstanceJoinQuery) Aggregate(fns ...AggregateFunc) *WorkflowInstanceJoinSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *WorkflowInstanceJoinQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !workflowinstancejoin.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if workflowinstancejoin.Policy == nil {
		return errors.New("ent: uninitialized workflowinstancejoin.Policy (forgotten import ent/runtime?)")
	}
	if err := workflowinstancejoin.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *WorkflowInstanceJoinQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WorkflowInstanceJoin, error) {
	var (
		nodes       = []*WorkflowInstanceJoin{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withInstance != nil,
		}
	)
	if _q.withInstance != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, workflowinstancejoin.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WorkflowInstanceJoin).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WorkflowInstanceJoin{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withInstance; query != nil {
		if err := _q.loadInstance(ctx, query, nodes, nil,
			func(n *WorkflowInstanceJoin, e *WorkflowInstance) { n.Edges.Instance = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *WorkflowInstanceJoinQuery) loadInstance(ctx context.Context, query *WorkflowInstanceQuery, nodes []*WorkflowInstanceJoin, init func(*WorkflowInstanceJoin), assign func(*WorkflowInstanceJoin, *WorkflowInstance)) error {
	ids := make([]uint32, 0, len(nodes))
	nodeids := make(map[uint32][]*WorkflowInstanceJoin)
	for i := range nodes {
		if nodes[i].instance_id == nil {
			continue
		}
		fk := *nodes[i].instance_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workflowinstance.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "instance_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *WorkflowInstanceJoinQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *WorkflowInstanceJoinQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(workflowinstancejoin.Table, workflowinstancejoin.Columns, sqlgraph.NewFieldSpec(workflowinstancejoin.FieldID, field.TypeUint32))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowinstancejoin.FieldID)
		for i := range fields {
			if fields[i] != workflowinstancejoin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *WorkflowInstanceJoinQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(workflowinstancejoin.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = workflowinstancejoin.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *WorkflowInstanceJoinQuery) Modify(modifiers ...func(s *sql.Selector)) *WorkflowInstanceJoinSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// WorkflowInstanceJoinGroupBy is the group-by builder for WorkflowInstanceJoin entities.
type WorkflowInstanceJoinGroupBy struct {
	selector
	build *WorkflowInstanceJoinQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *WorkflowInstanceJoinGroupBy) Aggregate(fns ...AggregateFunc) *WorkflowInstanceJoinGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *WorkflowInstanceJoinGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkflowInstanceJoinQuery, *WorkflowInstanceJoinGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *WorkflowInstanceJoinGroupBy) sqlScan(ctx context.Context, root *WorkflowInstanceJoinQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WorkflowInstanceJoinSelect is the builder for selecting fields of WorkflowInstanceJoin entities.
type WorkflowInstanceJoinSelect struct {
	*WorkflowInstanceJoinQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *WorkflowInstanceJoinSelect) Aggregate(fns ...AggregateFunc) *WorkflowInstanceJoinSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *WorkflowInstanceJoinSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkflowInstanceJoinQuery, *WorkflowInstanceJoinSelect](ctx, _s.WorkflowInstanceJoinQuery, _s, _s.inters, v)
}

func (_s *WorkflowInstanceJoinSelect) sqlScan(ctx context.Context, root *WorkflowInstanceJoinQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *WorkflowInstanceJoinSelect) Modify(modifiers ...func(s *sql.Selector)) *WorkflowInstanceJoinSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
