// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-oa/app/core/service/internal/data/ent/predicate"
	"go-wind-oa/app/core/service/internal/data/ent/workflowdelegation"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkflowDelegationUpdate is the builder for updating WorkflowDelegation entities.
type WorkflowDelegationUpdate struct {
	config
	hooks     []Hook
	mutation  *WorkflowDelegationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the WorkflowDelegationUpdate builder.
func (_u *WorkflowDelegationUpdate) Where(ps ...predicate.WorkflowDelegation) *WorkflowDelegationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkflowDelegationUpdate) SetUpdatedAt(v time.Time) *WorkflowDelegationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *WorkflowDelegationUpdate) SetNillableUpdatedAt(v *time.Time) *WorkflowDelegationUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *WorkflowDelegationUpdate) ClearUpdatedAt() *WorkflowDelegationUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *WorkflowDelegationUpdate) SetDeletedAt(v time.Time) *WorkflowDelegationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *WorkflowDelegationUpdate) SetNillableDeletedAt(v *time.Time) *WorkflowDelegationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *WorkflowDelegationUpdate) ClearDeletedAt() *WorkflowDelegationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *WorkflowDelegationUpdate) SetCreatedBy(v uint32) *WorkflowDelegationUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *WorkflowDelegationUpdate) SetNillableCreatedBy(v *uint32) *WorkflowDelegationUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *WorkflowDelegationUpdate) AddCreatedBy(v int32) *WorkflowDelegationUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *WorkflowDelegationUpdate) ClearCreatedBy() *WorkflowDelegationUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *WorkflowDelegationUpdate) SetUpdatedBy(v uint32) *WorkflowDelegationUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *WorkflowDelegationUpdate) SetNillableUpdatedBy(v *uint32) *WorkflowDelegationUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *WorkflowDelegationUpdate) AddUpdatedBy(v int32) *WorkflowDelegationUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *WorkflowDelegationUpdate) ClearUpdatedBy() *WorkflowDelegationUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *WorkflowDelegationUpdate) SetDeletedBy(v uint32) *WorkflowDelegationUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *WorkflowDelegationUpdate) SetNillableDeletedBy(v *uint32) *WorkflowDelegationUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *WorkflowDelegationUpdate) AddDeletedBy(v int32) *WorkflowDelegationUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *WorkflowDelegationUpdate) ClearDeletedBy() *WorkflowDelegationUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetDelegatorUserID sets the "delegator_user_id" field.
func (_u *WorkflowDelegationUpdate) SetDelegatorUserID(v uint32) *WorkflowDelegationUpdate {
	_u.mutation.ResetDelegatorUserID()
	_u.mutation.SetDelegatorUserID(v)
	return _u
}

// SetNillableDelegatorUserID sets the "delegator_user_id" field if the given value is not nil.
func (_u *WorkflowDelegationUpdate) SetNillableDelegatorUserID(v *uint32) *WorkflowDelegationUpdate {
	if v != nil {
		_u.SetDelegatorUserID(*v)
	}
	return _u
}

// AddDelegatorUserID adds value to the "delegator_user_id" field.
func (_u *WorkflowDelegationUpdate) AddDelegatorUserID(v int32) *WorkflowDelegationUpdate {
	_u.mutation.AddDelegatorUserID(v)
	return _u
}

// ClearDelegatorUserID clears the value of the "delegator_user_id" field.
func (_u *WorkflowDelegationUpdate) ClearDelegatorUserID() *WorkflowDelegationUpdate {
	_u.mutation.ClearDelegatorUserID()
	return _u
}

// SetDelegateUserID sets the "delegate_user_id" field.
func (_u *WorkflowDelegationUpdate) SetDelegateUserID(v uint32) *WorkflowDelegationUpdate {
	_u.mutation.ResetDelegateUserID()
	_u.mutation.SetDelegateUserID(v)
	return _u
}

// SetNillableDelegateUserID sets the "delegate_user_id" field if the given value is not nil.
func (_u *WorkflowDelegationUpdate) SetNillableDelegateUserID(v *uint32) *WorkflowDelegationUpdate {
	if v != nil {
		_u.SetDelegateUserID(*v)
	}
	return _u
}

// AddDelegateUserID adds value to the "delegate_user_id" field.
func (_u *WorkflowDelegationUpdate) AddDelegateUserID(v int32) *WorkflowDelegationUpdate {
	_u.mutation.AddDelegateUserID(v)
	return _u
}

// ClearDelegateUserID clears the value of the "delegate_user_id" field.
func (_u *WorkflowDelegationUpdate) ClearDelegateUserID() *WorkflowDelegationUpdate {
	_u.mutation.ClearDelegateUserID()
	return _u
}

// Mutation returns the WorkflowDelegationMutation object of the builder.
func (_u *WorkflowDelegationUpdate) Mutation() *WorkflowDelegationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkflowDelegationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowDelegationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkflowDelegationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowDelegationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *WorkflowDelegationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WorkflowDelegationUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *WorkflowDelegationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(workflowdelegation.Table, workflowdelegation.Columns, sqlgraph.NewFieldSpec(workflowdelegation.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(workflowdelegation.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workflowdelegation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(workflowdelegation.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(workflowdelegation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(workflowdelegation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(workflowdelegation.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(workflowdelegation.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(workflowdelegation.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(workflowdelegation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(workflowdelegation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(workflowdelegation.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(workflowdelegation.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(workflowdelegation.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(workflowdelegation.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(workflowdelegation.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.DelegatorUserID(); ok {
		_spec.SetField(workflowdelegation.FieldDelegatorUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDelegatorUserID(); ok {
		_spec.AddField(workflowdelegation.FieldDelegatorUserID, field.TypeUint32, value)
	}
	if _u.mutation.DelegatorUserIDCleared() {
		_spec.ClearField(workflowdelegation.FieldDelegatorUserID, field.TypeUint32)
	}
	if value, ok := _u.mutation.DelegateUserID(); ok {
		_spec.SetField(workflowdelegation.FieldDelegateUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDelegateUserID(); ok {
		_spec.AddField(workflowdelegation.FieldDelegateUserID, field.TypeUint32, value)
	}
	if _u.mutation.DelegateUserIDCleared() {
		_spec.ClearField(workflowdelegation.FieldDelegateUserID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowdelegation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkflowDelegationUpdateOne is the builder for updating a single WorkflowDelegation entity.
type WorkflowDelegationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *WorkflowDelegationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkflowDelegationUpdateOne) SetUpdatedAt(v time.Time) *WorkflowDelegationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *WorkflowDelegationUpdateOne) SetNillableUpdatedAt(v *time.Time) *WorkflowDelegationUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *WorkflowDelegationUpdateOne) ClearUpdatedAt() *WorkflowDelegationUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *WorkflowDelegationUpdateOne) SetDeletedAt(v time.Time) *WorkflowDelegationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *WorkflowDelegationUpdateOne) SetNillableDeletedAt(v *time.Time) *WorkflowDelegationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *WorkflowDelegationUpdateOne) ClearDeletedAt() *WorkflowDelegationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *WorkflowDelegationUpdateOne) SetCreatedBy(v uint32) *WorkflowDelegationUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *WorkflowDelegationUpdateOne) SetNillableCreatedBy(v *uint32) *WorkflowDelegationUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *WorkflowDelegationUpdateOne) AddCreatedBy(v int32) *WorkflowDelegationUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *WorkflowDelegationUpdateOne) ClearCreatedBy() *WorkflowDelegationUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *WorkflowDelegationUpdateOne) SetUpdatedBy(v uint32) *WorkflowDelegationUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *WorkflowDelegationUpdateOne) SetNillableUpdatedBy(v *uint32) *WorkflowDelegationUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *WorkflowDelegationUpdateOne) AddUpdatedBy(v int32) *WorkflowDelegationUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *WorkflowDelegationUpdateOne) ClearUpdatedBy() *WorkflowDelegationUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *WorkflowDelegationUpdateOne) SetDeletedBy(v uint32) *WorkflowDelegationUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *WorkflowDelegationUpdateOne) SetNillableDeletedBy(v *uint32) *WorkflowDelegationUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *WorkflowDelegationUpdateOne) AddDeletedBy(v int32) *WorkflowDelegationUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *WorkflowDelegationUpdateOne) ClearDeletedBy() *WorkflowDelegationUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetDelegatorUserID sets the "delegator_user_id" field.
func (_u *WorkflowDelegationUpdateOne) SetDelegatorUserID(v uint32) *WorkflowDelegationUpdateOne {
	_u.mutation.ResetDelegatorUserID()
	_u.mutation.SetDelegatorUserID(v)
	return _u
}

// SetNillableDelegatorUserID sets the "delegator_user_id" field if the given value is not nil.
func (_u *WorkflowDelegationUpdateOne) SetNillableDelegatorUserID(v *uint32) *WorkflowDelegationUpdateOne {
	if v != nil {
		_u.SetDelegatorUserID(*v)
	}
	return _u
}

// AddDelegatorUserID adds value to the "delegator_user_id" field.
func (_u *WorkflowDelegationUpdateOne) AddDelegatorUserID(v int32) *WorkflowDelegationUpdateOne {
	_u.mutation.AddDelegatorUserID(v)
	return _u
}

// ClearDelegatorUserID clears the value of the "delegator_user_id" field.
func (_u *WorkflowDelegationUpdateOne) ClearDelegatorUserID() *WorkflowDelegationUpdateOne {
	_u.mutation.ClearDelegatorUserID()
	return _u
}

// SetDelegateUserID sets the "delegate_user_id" field.
func (_u *WorkflowDelegationUpdateOne) SetDelegateUserID(v uint32) *WorkflowDelegationUpdateOne {
	_u.mutation.ResetDelegateUserID()
	_u.mutation.SetDelegateUserID(v)
	return _u
}

// SetNillableDelegateUserID sets the "delegate_user_id" field if the given value is not nil.
func (_u *WorkflowDelegationUpdateOne) SetNillableDelegateUserID(v *uint32) *WorkflowDelegationUpdateOne {
	if v != nil {
		_u.SetDelegateUserID(*v)
	}
	return _u
}

// AddDelegateUserID adds value to the "delegate_user_id" field.
func (_u *WorkflowDelegationUpdateOne) AddDelegateUserID(v int32) *WorkflowDelegationUpdateOne {
	_u.mutation.AddDelegateUserID(v)
	return _u
}

// ClearDelegateUserID clears the value of the "delegate_user_id" field.
func (_u *WorkflowDelegationUpdateOne) ClearDelegateUserID() *WorkflowDelegationUpdateOne {
	_u.mutation.ClearDelegateUserID()
	return _u
}

// Mutation returns the WorkflowDelegationMutation object of the builder.
func (_u *WorkflowDelegationUpdateOne) Mutation() *WorkflowDelegationMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkflowDelegationUpdate builder.
func (_u *WorkflowDelegationUpdateOne) Where(ps ...predicate.WorkflowDelegation) *WorkflowDelegationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkflowDelegationUpdateOne) Select(field string, fields ...string) *WorkflowDelegationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkflowDelegation entity.
func (_u *WorkflowDelegationUpdateOne) Save(ctx context.Context) (*WorkflowDelegation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowDelegationUpdateOne) SaveX(ctx context.Context) *WorkflowDelegation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkflowDelegationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowDelegationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *WorkflowDelegationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WorkflowDelegationUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *WorkflowDelegationUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowDelegation, err error) {
	_spec := sqlgraph.NewUpdateSpec(workflowdelegation.Table, workflowdelegation.Columns, sqlgraph.NewFieldSpec(workflowdelegation.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowDelegation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowdelegation.FieldID)
		for _, f := range fields {
			if !workflowdelegation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflowdelegation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(workflowdelegation.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workflowdelegation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(workflowdelegation.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(workflowdelegation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(workflowdelegation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(workflowdelegation.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(workflowdelegation.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(workflowdelegation.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(workflowdelegation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(workflowdelegation.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(workflowdelegation.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(workflowdelegation.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(workflowdelegation.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(workflowdelegation.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(workflowdelegation.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.DelegatorUserID(); ok {
		_spec.SetField(workflowdelegation.FieldDelegatorUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDelegatorUserID(); ok {
		_spec.AddField(workflowdelegation.FieldDelegatorUserID, field.TypeUint32, value)
	}
	if _u.mutation.DelegatorUserIDCleared() {
		_spec.ClearField(workflowdelegation.FieldDelegatorUserID, field.TypeUint32)
	}
	if value, ok := _u.mutation.DelegateUserID(); ok {
		_spec.SetField(workflowdelegation.FieldDelegateUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDelegateUserID(); ok {
		_spec.AddField(workflowdelegation.FieldDelegateUserID, field.TypeUint32, value)
	}
	if _u.mutation.DelegateUserIDCleared() {
		_spec.ClearField(workflowdelegation.FieldDelegateUserID, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &WorkflowDelegation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowdelegation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
