// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"go-wind-oa/app/core/service/internal/data/ent/workflowdefinition"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// OA工作流定义表
type WorkflowDefinition struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 备注
	Remark *string `json:"remark,omitempty"`
	// 流程名称
	Name *string `json:"name,omitempty"`
	// 流程编码
	Code *string `json:"code,omitempty"`
	// 版本号
	Version *uint32 `json:"version,omitempty"`
	// 描述
	Description *string `json:"description,omitempty"`
	// 节点配置(JSON)
	NodeConfig any `json:"node_config,omitempty"`
	// 动态表单schema(JSON)
	FormSchema any `json:"form_schema,omitempty"`
	// 定义状态
	DefinitionStatus workflowdefinition.DefinitionStatus `json:"definition_status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkflowDefinitionQuery when eager-loading is set.
	Edges        WorkflowDefinitionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WorkflowDefinitionEdges holds the relations/edges for other nodes in the graph.
type WorkflowDefinitionEdges struct {
	// Instances holds the value of the instances edge.
	Instances []*WorkflowInstance `json:"instances,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// InstancesOrErr returns the Instances value or an error if the edge
// was not loaded in eager-loading.
func (e WorkflowDefinitionEdges) InstancesOrErr() ([]*WorkflowInstance, error) {
	if e.loadedTypes[0] {
		return e.Instances, nil
	}
	return nil, &NotLoadedError{edge: "instances"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkflowDefinition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workflowdefinition.FieldNodeConfig, workflowdefinition.FieldFormSchema:
			values[i] = new([]byte)
		case workflowdefinition.FieldID, workflowdefinition.FieldCreatedBy, workflowdefinition.FieldUpdatedBy, workflowdefinition.FieldDeletedBy, workflowdefinition.FieldTenantID, workflowdefinition.FieldVersion:
			values[i] = new(sql.NullInt64)
		case workflowdefinition.FieldRemark, workflowdefinition.FieldName, workflowdefinition.FieldCode, workflowdefinition.FieldDescription, workflowdefinition.FieldDefinitionStatus:
			values[i] = new(sql.NullString)
		case workflowdefinition.FieldCreatedAt, workflowdefinition.FieldUpdatedAt, workflowdefinition.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkflowDefinition fields.
func (_m *WorkflowDefinition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workflowdefinition.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case workflowdefinition.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case workflowdefinition.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case workflowdefinition.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case workflowdefinition.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case workflowdefinition.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case workflowdefinition.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case workflowdefinition.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case workflowdefinition.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		case workflowdefinition.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case workflowdefinition.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = new(string)
				*_m.Code = value.String
			}
		case workflowdefinition.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = new(uint32)
				*_m.Version = uint32(value.Int64)
			}
		case workflowdefinition.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case workflowdefinition.FieldNodeConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field node_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NodeConfig); err != nil {
					return fmt.Errorf("unmarshal field node_config: %w", err)
				}
			}
		case workflowdefinition.FieldFormSchema:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field form_schema", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.FormSchema); err != nil {
					return fmt.Errorf("unmarshal field form_schema: %w", err)
				}
			}
		case workflowdefinition.FieldDefinitionStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field definition_status", values[i])
			} else if value.Valid {
				_m.DefinitionStatus = workflowdefinition.DefinitionStatus(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkflowDefinition.
// This includes values selected through modifiers, order, etc.
func (_m *WorkflowDefinition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInstances queries the "instances" edge of the WorkflowDefinition entity.
func (_m *WorkflowDefinition) QueryInstances() *WorkflowInstanceQuery {
	return NewWorkflowDefinitionClient(_m.config).QueryInstances(_m)
}

// Update returns a builder for updating this WorkflowDefinition.
// Note that you need to call WorkflowDefinition.Unwrap() before calling this method if this WorkflowDefinition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkflowDefinition) Update() *WorkflowDefinitionUpdateOne {
	return NewWorkflowDefinitionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkflowDefinition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkflowDefinition) Unwrap() *WorkflowDefinition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkflowDefinition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkflowDefinition) String() string {
	var builder strings.Builder
	builder.WriteString("WorkflowDefinition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Code; v != nil {
		builder.WriteString("code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Version; v != nil {
		builder.WriteString("version=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("node_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeConfig))
	builder.WriteString(", ")
	builder.WriteString("form_schema=")
	builder.WriteString(fmt.Sprintf("%v", _m.FormSchema))
	builder.WriteString(", ")
	builder.WriteString("definition_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefinitionStatus))
	builder.WriteByte(')')
	return builder.String()
}

// WorkflowDefinitions is a parsable slice of WorkflowDefinition.
type WorkflowDefinitions []*WorkflowDefinition
