syntax = "proto3";

package admin.service.v1;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "pagination/v1/pagination.proto";

import "content/service/v1/section.proto";

// 页面区块服务
service SectionService {
  // 获取区块列表
  rpc List (pagination.PagingRequest) returns (content.service.v1.ListSectionResponse) {
    option (google.api.http) = {
      get: "/admin/v1/sections"
    };
  }

  // 获取区块数据
  rpc Get (content.service.v1.GetSectionRequest) returns (content.service.v1.Section) {
    option (google.api.http) = {
      get: "/admin/v1/sections/{id}"
    };
  }

  // 创建区块
  rpc Create (content.service.v1.CreateSectionRequest) returns (content.service.v1.Section) {
    option (google.api.http) = {
      post: "/admin/v1/sections"
      body: "*"
    };
  }

  // 更新区块
  rpc Update (content.service.v1.UpdateSectionRequest) returns (content.service.v1.Section) {
    option (google.api.http) = {
      put: "/admin/v1/sections/{id}"
      body: "*"
    };
  }

  // 删除区块
  rpc Delete (content.service.v1.DeleteSectionRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/admin/v1/sections/{id}"
    };
  }
}
