// Code generated by ent, DO NOT EDIT.

package workflowinstance

import (
	"go-wind-oa/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldDeletedBy, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldTenantID, v))
}

// CurrentNodeIndex applies equality check predicate on the "current_node_index" field. It's identical to CurrentNodeIndexEQ.
func CurrentNodeIndex(v int) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldCurrentNodeIndex, v))
}

// FormData applies equality check predicate on the "form_data" field. It's identical to FormDataEQ.
func FormData(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldFormData, v))
}

// BusinessType applies equality check predicate on the "business_type" field. It's identical to BusinessTypeEQ.
func BusinessType(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldBusinessType, v))
}

// BusinessID applies equality check predicate on the "business_id" field. It's identical to BusinessIDEQ.
func BusinessID(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldBusinessID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotNull(FieldDeletedBy))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotNull(FieldTenantID))
}

// InstanceStatusEQ applies the EQ predicate on the "instance_status" field.
func InstanceStatusEQ(v InstanceStatus) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldInstanceStatus, v))
}

// InstanceStatusNEQ applies the NEQ predicate on the "instance_status" field.
func InstanceStatusNEQ(v InstanceStatus) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNEQ(FieldInstanceStatus, v))
}

// InstanceStatusIn applies the In predicate on the "instance_status" field.
func InstanceStatusIn(vs ...InstanceStatus) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIn(FieldInstanceStatus, vs...))
}

// InstanceStatusNotIn applies the NotIn predicate on the "instance_status" field.
func InstanceStatusNotIn(vs ...InstanceStatus) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotIn(FieldInstanceStatus, vs...))
}

// InstanceStatusIsNil applies the IsNil predicate on the "instance_status" field.
func InstanceStatusIsNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIsNull(FieldInstanceStatus))
}

// InstanceStatusNotNil applies the NotNil predicate on the "instance_status" field.
func InstanceStatusNotNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotNull(FieldInstanceStatus))
}

// CurrentNodeIndexEQ applies the EQ predicate on the "current_node_index" field.
func CurrentNodeIndexEQ(v int) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldCurrentNodeIndex, v))
}

// CurrentNodeIndexNEQ applies the NEQ predicate on the "current_node_index" field.
func CurrentNodeIndexNEQ(v int) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNEQ(FieldCurrentNodeIndex, v))
}

// CurrentNodeIndexIn applies the In predicate on the "current_node_index" field.
func CurrentNodeIndexIn(vs ...int) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIn(FieldCurrentNodeIndex, vs...))
}

// CurrentNodeIndexNotIn applies the NotIn predicate on the "current_node_index" field.
func CurrentNodeIndexNotIn(vs ...int) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotIn(FieldCurrentNodeIndex, vs...))
}

// CurrentNodeIndexGT applies the GT predicate on the "current_node_index" field.
func CurrentNodeIndexGT(v int) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGT(FieldCurrentNodeIndex, v))
}

// CurrentNodeIndexGTE applies the GTE predicate on the "current_node_index" field.
func CurrentNodeIndexGTE(v int) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGTE(FieldCurrentNodeIndex, v))
}

// CurrentNodeIndexLT applies the LT predicate on the "current_node_index" field.
func CurrentNodeIndexLT(v int) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLT(FieldCurrentNodeIndex, v))
}

// CurrentNodeIndexLTE applies the LTE predicate on the "current_node_index" field.
func CurrentNodeIndexLTE(v int) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLTE(FieldCurrentNodeIndex, v))
}

// CurrentNodeIndexIsNil applies the IsNil predicate on the "current_node_index" field.
func CurrentNodeIndexIsNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIsNull(FieldCurrentNodeIndex))
}

// CurrentNodeIndexNotNil applies the NotNil predicate on the "current_node_index" field.
func CurrentNodeIndexNotNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotNull(FieldCurrentNodeIndex))
}

// FormDataEQ applies the EQ predicate on the "form_data" field.
func FormDataEQ(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldFormData, v))
}

// FormDataNEQ applies the NEQ predicate on the "form_data" field.
func FormDataNEQ(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNEQ(FieldFormData, v))
}

// FormDataIn applies the In predicate on the "form_data" field.
func FormDataIn(vs ...string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIn(FieldFormData, vs...))
}

// FormDataNotIn applies the NotIn predicate on the "form_data" field.
func FormDataNotIn(vs ...string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotIn(FieldFormData, vs...))
}

// FormDataGT applies the GT predicate on the "form_data" field.
func FormDataGT(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGT(FieldFormData, v))
}

// FormDataGTE applies the GTE predicate on the "form_data" field.
func FormDataGTE(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGTE(FieldFormData, v))
}

// FormDataLT applies the LT predicate on the "form_data" field.
func FormDataLT(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLT(FieldFormData, v))
}

// FormDataLTE applies the LTE predicate on the "form_data" field.
func FormDataLTE(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLTE(FieldFormData, v))
}

// FormDataContains applies the Contains predicate on the "form_data" field.
func FormDataContains(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldContains(FieldFormData, v))
}

// FormDataHasPrefix applies the HasPrefix predicate on the "form_data" field.
func FormDataHasPrefix(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldHasPrefix(FieldFormData, v))
}

// FormDataHasSuffix applies the HasSuffix predicate on the "form_data" field.
func FormDataHasSuffix(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldHasSuffix(FieldFormData, v))
}

// FormDataIsNil applies the IsNil predicate on the "form_data" field.
func FormDataIsNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIsNull(FieldFormData))
}

// FormDataNotNil applies the NotNil predicate on the "form_data" field.
func FormDataNotNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotNull(FieldFormData))
}

// FormDataEqualFold applies the EqualFold predicate on the "form_data" field.
func FormDataEqualFold(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEqualFold(FieldFormData, v))
}

// FormDataContainsFold applies the ContainsFold predicate on the "form_data" field.
func FormDataContainsFold(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldContainsFold(FieldFormData, v))
}

// BusinessTypeEQ applies the EQ predicate on the "business_type" field.
func BusinessTypeEQ(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldBusinessType, v))
}

// BusinessTypeNEQ applies the NEQ predicate on the "business_type" field.
func BusinessTypeNEQ(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNEQ(FieldBusinessType, v))
}

// BusinessTypeIn applies the In predicate on the "business_type" field.
func BusinessTypeIn(vs ...string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIn(FieldBusinessType, vs...))
}

// BusinessTypeNotIn applies the NotIn predicate on the "business_type" field.
func BusinessTypeNotIn(vs ...string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotIn(FieldBusinessType, vs...))
}

// BusinessTypeGT applies the GT predicate on the "business_type" field.
func BusinessTypeGT(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGT(FieldBusinessType, v))
}

// BusinessTypeGTE applies the GTE predicate on the "business_type" field.
func BusinessTypeGTE(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGTE(FieldBusinessType, v))
}

// BusinessTypeLT applies the LT predicate on the "business_type" field.
func BusinessTypeLT(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLT(FieldBusinessType, v))
}

// BusinessTypeLTE applies the LTE predicate on the "business_type" field.
func BusinessTypeLTE(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLTE(FieldBusinessType, v))
}

// BusinessTypeContains applies the Contains predicate on the "business_type" field.
func BusinessTypeContains(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldContains(FieldBusinessType, v))
}

// BusinessTypeHasPrefix applies the HasPrefix predicate on the "business_type" field.
func BusinessTypeHasPrefix(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldHasPrefix(FieldBusinessType, v))
}

// BusinessTypeHasSuffix applies the HasSuffix predicate on the "business_type" field.
func BusinessTypeHasSuffix(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldHasSuffix(FieldBusinessType, v))
}

// BusinessTypeIsNil applies the IsNil predicate on the "business_type" field.
func BusinessTypeIsNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIsNull(FieldBusinessType))
}

// BusinessTypeNotNil applies the NotNil predicate on the "business_type" field.
func BusinessTypeNotNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotNull(FieldBusinessType))
}

// BusinessTypeEqualFold applies the EqualFold predicate on the "business_type" field.
func BusinessTypeEqualFold(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEqualFold(FieldBusinessType, v))
}

// BusinessTypeContainsFold applies the ContainsFold predicate on the "business_type" field.
func BusinessTypeContainsFold(v string) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldContainsFold(FieldBusinessType, v))
}

// BusinessIDEQ applies the EQ predicate on the "business_id" field.
func BusinessIDEQ(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldEQ(FieldBusinessID, v))
}

// BusinessIDNEQ applies the NEQ predicate on the "business_id" field.
func BusinessIDNEQ(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNEQ(FieldBusinessID, v))
}

// BusinessIDIn applies the In predicate on the "business_id" field.
func BusinessIDIn(vs ...uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIn(FieldBusinessID, vs...))
}

// BusinessIDNotIn applies the NotIn predicate on the "business_id" field.
func BusinessIDNotIn(vs ...uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotIn(FieldBusinessID, vs...))
}

// BusinessIDGT applies the GT predicate on the "business_id" field.
func BusinessIDGT(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGT(FieldBusinessID, v))
}

// BusinessIDGTE applies the GTE predicate on the "business_id" field.
func BusinessIDGTE(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldGTE(FieldBusinessID, v))
}

// BusinessIDLT applies the LT predicate on the "business_id" field.
func BusinessIDLT(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLT(FieldBusinessID, v))
}

// BusinessIDLTE applies the LTE predicate on the "business_id" field.
func BusinessIDLTE(v uint32) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldLTE(FieldBusinessID, v))
}

// BusinessIDIsNil applies the IsNil predicate on the "business_id" field.
func BusinessIDIsNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldIsNull(FieldBusinessID))
}

// BusinessIDNotNil applies the NotNil predicate on the "business_id" field.
func BusinessIDNotNil() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.FieldNotNull(FieldBusinessID))
}

// HasDefinition applies the HasEdge predicate on the "definition" edge.
func HasDefinition() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DefinitionTable, DefinitionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDefinitionWith applies the HasEdge predicate on the "definition" edge with a given conditions (other predicates).
func HasDefinitionWith(preds ...predicate.WorkflowDefinition) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(func(s *sql.Selector) {
		step := newDefinitionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTasks applies the HasEdge predicate on the "tasks" edge.
func HasTasks() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTasksWith applies the HasEdge predicate on the "tasks" edge with a given conditions (other predicates).
func HasTasksWith(preds ...predicate.WorkflowTask) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(func(s *sql.Selector) {
		step := newTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLogs applies the HasEdge predicate on the "logs" edge.
func HasLogs() predicate.WorkflowInstance {
	return predicate.WorkflowInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LogsTable, LogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLogsWith applies the HasEdge predicate on the "logs" edge with a given conditions (other predicates).
func HasLogsWith(preds ...predicate.WorkflowLog) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(func(s *sql.Selector) {
		step := newLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkflowInstance) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkflowInstance) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkflowInstance) predicate.WorkflowInstance {
	return predicate.WorkflowInstance(sql.NotPredicates(p))
}
