client:
  grpc:
    timeout: 120s
    middleware:
      enable_logging: true
      enable_recovery: true
      enable_tracing: true
      enable_validate: true
      enable_circuit_breaker: true
      enable_metadata: true
      auth:
        method: "HS256"
        key: "${jwt_signing_key:dev_only_change_me_in_prod}"
